### ISSUE TITLE
Slidy Start Complete (-c) is breaking the app

### ISSUE THREAD

**Issue by Bwolfs2** [Flutterando/slidy#100]
![image](https://user-images.githubusercontent.com/4654514/72212774-8a30ae00-34c1-11ea-9c31-27a1484339f3.png)

What we gonna do?

**Comment by guilhermeinovando** [comment]
Add in your dependencies:
flutter_localizations:
    sdk: flutter

like
flutter:
    sdk: flutter

my complete section of code like this:
dependencies:
  dio: ^3.0.8
  flutter_mobx: ^0.3.6
  mobx: ^0.4.0+1
  flutter_modular: ^0.3.3+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
