### ISSUE TITLE
Cannot run slidy...

### ISSUE THREAD

**Issue by GQAdonis** [Flutterando/slidy#103]
I have a problem where after have activated slidy, I get the following error when running ANY command:

Can't load Kernel binary: Invalid kernel binary format version.

I am running this latest flutter version:

Flutter 1.14.2-pre.27 • channel master • https://github.com/flutter/flutter.git
Framework • revision 01f19ee6d4 (69 minutes ago) • 2020-01-16 16:41:06 -0500
Engine • revision 6693dd7518
Tools • Dart 2.8.0 (build 2.8.0-dev.2.0 009537bbf0)

Any ideas?

**Comment by Bwolfs2** [comment]
Try run on other channel, i guess this channel are using Dart 2.8, i think is this.

**Comment by alexwbuschle** [comment]
It's working at dev's channel
```
Flutter 1.14.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision c88320458e (33 hours ago) • 2020-01-15 11:38:02 -0500
Engine • revision bc41ab5139
Tools • Dart 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)
```

**Comment by phcaraujo** [comment]
> Try upgrade dart-sdk. works with me
> 
> https://dart.dev/get-dart#install

Consegui resolver fazendo esse procedimento, obrigado.

**Comment by alexwbuschle** [comment]
brew users have 2 options:
- Keep flutter on the stable branch and use the default `brew install dart` (it's the dart stable version 2.7.0)
- If you want to be on the edge, use flutter on the master/dev channel, but you need to switch the brew dart to devel :)

**Comment by jacobaraujo7** [comment]
Problem Fixed. Issue Closed :)
