### ISSUE TITLE
Gerenciador de estado não detectado no comando generate quando o primeiro é uma dependência transitiva

### ISSUE THREAD

**Issue by icarohs7** [Flutterando/slidy#105]
&nbsp;&nbsp;Atualmente se, por exemplo, você utilizar o modular + mobx mas os mesmos forem dependências transitivas do projeto, ao executar o comando `slidy g m -c modules/nome_modulo` a biblioteca de gerenciamento de estado não é detectada corretamente e o módulo acaba sendo criado utilizando Bloc e modulos do package bloc_pattern como fallback.
&nbsp;&nbsp;Creio que a forma mais fácil de solucionar este problema seja adicionando flags ao comando generate para permitir ao usuário selecionar a estrutura que utiliza.
Exemplo da ideia a ser utilizada:
```
slidy g m -c -m modules/nome_module  //-m seria mobx
slidy g m -c -b modules/nome_module  //-b seria bloc_pattern
slidy g m -c -f modules/nome_module  //-f seria flutter_bloc
```
Caso a flag não seja informada, o comportamento padrão(atual) é adotado.

**Comment by jacobaraujo7** [comment]
nice!
