### ISSUE TITLE
Modulo padrão para o generate

### ISSUE THREAD

**Issue by skay1994** [Flutterando/slidy#109]
Uso o Laravel com modulos no backend, e o pacote *nWidart/laravel-modules* possui o comando *module:use* que define um modulo padrão para qualquer outro comando de geração de codigo,

Ex: para criar uma nova migration seria: ``` $ php artisan module:make-migration Nome Modulo ```
porem com o comando ``` $ php artisan module:use Modulo``` iria simplificar para ``` $ php artisan module:make-migration Nome```

Dentro do slidy imagino algo no estilo: ``` $ slidy g u/use login``` e o depois ``` $ slidy g p pages/login ``` e o arquivo final ficaria ``` lib/app/modules/login/pages/login_page.dart ```

**Comment by rodrigolmacedo** [comment]
Seria interessante, às vezes, eu coloco o path errado e tenho que ficar apagando(nos modulos e testes) XD
