### ISSUE TITLE
gerar arquivos stateful

### ISSUE THREAD

**Issue by hevertonpablo** [Flutterando/slidy#116]
Senti a necessidade de um comando pra gerar arquivos stateful.

slidy g w pages/contato gerar um arquivo stateless, deveria ter um comando pra gerar um arquivo stateful.

**Comment by WilliamCunhaCardoso** [comment]
algo como slidy g w  -s/--stateful pages/contato

**Comment by toshiossada** [comment]
algo como slidy g w -sf
