### ISSUE TITLE
Arquivo .g.dart não gera se o nome do arquivo contém (_) underline

### ISSUE THREAD

**Issue by dotnunes** [Flutterando/slidy#121]
Comando: slidy g p ui/android/pages/tela_inicio
Build Runner não acha o arquivo **tela_inicio_controller.dart**, porque o part'' fica errado.

import 'package:mobx/mobx.dart';
**part 'telainicio_controller.g.dart';**

class TelaInicioController = _TelaInicioBase with _$TelaInicioController;

abstract class _TelaInicioBase with Store {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}

**Comment by Bwolfs2** [comment]
Ja foi corrigido mas acho que ainda nao foi liberada a nova versão

**Comment by lucascorrea30** [comment]
no meu caso, ele nao está gerando o arquivo controller.g.dart

**Comment by Bwolfs2** [comment]
Ele nao gera mesmo @lucascorrea30 , quem vai gerar o .g é o build_runner, entao quando vc rodar o flutter pub run build_runner build ou watch ele vai gerar o .g pra voce

**Comment by lucascorrea30** [comment]
mas da erro _(pub finished with exit code 78)_ dos outros ja criados... eu sempre preciso remover os .g.dart e criar de novo?
