### ISSUE TITLE
slidy start não funciona de forma adequada no Android Studio

### ISSUE THREAD

**Issue by ThiagoFTelles** [Flutterando/slidy#123]
Olá!

Ao executar o comando "slidy start" (estou usando a versão 1.5.3) não consigo usar as setas do teclado para selecionar as opções. E se apenas aperto enter acontece o seguinte:

`[2J[0;0H
[38;5;10mSlidy CLI Interative
[0m
[38;5;11mWARN: What Provider System do you want to use?[0m
[38;5;10mflutter_modular (default)[0m
[38;5;15mbloc_pattern[0m

Use ↑↓ (keyboard arrows)
Press 'q' to quit.
[2J[0;0H
[38;5;10mSlidy CLI Interative
[0m
[38;5;11mWARN: Choose a state manager[0m
[38;5;10mmobx (default)[0m
[38;5;15mflutter_bloc[0m
[38;5;15mBLoC with rxdart[0m

Use ↑↓ (keyboard arrows)
Press 'q' to quit.
[38;5;9mERROR: The lib folder must be empty[0m
`
Ele dá este erro mesmo se eu apagar os arquivos das pastas 'lib' e 'test' manualmente.

EDIT: Consegui instalar apenas apertando ENTER e usando as configurações default após apagar completamente as pastas 'lib' e 'test' (não apenas os arquivos).

**Comment by Bwolfs2** [comment]
Qual versão você esta usando @ThiagoFTelles ? Qual SO? Qual versão do Android Studio?

Testei aqui na ultima versão do AS e esta funcionando normalmente.

![image](https://user-images.githubusercontent.com/4654514/76339016-54008680-62d8-11ea-83d4-eb475a7fe09e.png)

**Comment by laerciomonteiro** [comment]
Estou exatamente com o mesmo problema. Atualizei para a versão mais recente do Android Studio (3.6), atualizei o SDK do Dart para a última versão (2.7.1), atualizei o Flutter, executei os comandos flutter clean e flutter doctor e também atualizei o Slidy para a versão (2.0.0+1), mas nada resolveu esse problema.

**Comment by laerciomonteiro** [comment]
Até mesmo na versão mais recente do Android o problema persiste. Acredito que isso seja um problema na própria estrutura do Slidy CLI Interactive.

**Comment by laerciomonteiro** [comment]
> Qual versão você esta usando @ThiagoFTelles ? Qual SO? Qual versão do Android Studio?
> 
> Testei aqui na ultima versão do AS e esta funcionando normalmente.
> 
> ![image](https://user-images.githubusercontent.com/4654514/76339016-54008680-62d8-11ea-83d4-eb475a7fe09e.png)

Até mesmo na versão mais recente do Android o problema persiste. Acredito que isso seja um problema na própria estrutura do Slidy CLI Interactive.

**Comment by laerciomonteiro** [comment]
> Olá!
> 
> Ao executar o comando "slidy start" (estou usando a versão 1.5.3) não consigo usar as setas do teclado para selecionar as opções. E se apenas aperto enter acontece o seguinte:
> 
> `[2J[0;0H
> [38;5;10mSlidy CLI Interative
> [0m
> [38;5;11mWARN: What Provider System do you want to use?[0m
> [38;5;10mflutter_modular (default)[0m
> [38;5;15mbloc_pattern[0m
> 
> Use ↑↓ (keyboard arrows)
> Press 'q' to quit.
> [2J[0;0H
> [38;5;10mSlidy CLI Interative
> [0m
> [38;5;11mWARN: Choose a state manager[0m
> [38;5;10mmobx (default)[0m
> [38;5;15mflutter_bloc[0m
> [38;5;15mBLoC with rxdart[0m
> 
> Use ↑↓ (keyboard arrows)
> Press 'q' to quit.
> [38;5;9mERROR: The lib folder must be empty[0m
> `
> Ele dá este erro mesmo se eu apagar os arquivos das pastas 'lib' e 'test' manualmente.
> 
> EDIT: Consegui instalar apenas apertando ENTER e usando as configurações default após apagar completamente as pastas 'lib' e 'test' (não apenas os arquivos).

Estou exatamente com o mesmo problema. Atualizei para a versão mais recente do Android Studio (3.6), atualizei o SDK do Dart para a última versão (2.7.1), atualizei o Flutter, executei os comandos flutter clean e flutter doctor e também atualizei o Slidy para a versão (2.0.0+1), mas nada resolveu esse problema.

**Comment by laerciomonteiro** [comment]
> Qual versão você esta usando @ThiagoFTelles ? Qual SO? Qual versão do Android Studio?
> 
> Testei aqui na ultima versão do AS e esta funcionando normalmente.
> 
> ![image](https://user-images.githubusercontent.com/4654514/76339016-54008680-62d8-11ea-83d4-eb475a7fe09e.png)

@Bwolfs2 , até mesmo na versão mais recente do Android o problema persiste. Acredito que isso seja um problema na própria estrutura do Slidy CLI Interactive.

**Comment by ThiagoFTelles** [comment]
> Qual versão você esta usando @ThiagoFTelles ? Qual SO? Qual versão do Android Studio?
> 
> Testei aqui na ultima versão do AS e esta funcionando normalmente.
> 
> ![image](https://user-images.githubusercontent.com/4654514/76339016-54008680-62d8-11ea-83d4-eb475a7fe09e.png)

Fala cara! Curti muito seu vídeo sobre as 5 ferramentas que devemos conhecer! Foi de lá que comecei a usar o slidy (e das aulas de mobx). Obrigado!

Seguem informações:

SO: Win7 Ultimate SP1
Slidy: 1.5.3
Android Studio: 3.6.1

**Comment by laerciomonteiro** [comment]
@ThiagoFTelles conseguiu algo?

**Comment by Bwolfs2** [comment]
Marca um horario e compartilha a tela la no Discord pra nós tentar resolver isso

**Comment by laerciomonteiro** [comment]
Beleza. Podemos acertar no Telegram?

**Comment by ThiagoFTelles** [comment]
Fala galera, tudo bem com vocês?
Eu trabalho a masrugada toda, então se quiserem podemos fazer uma call a qualquer dia a noite e testarmos no meu pc.

**Comment by laerciomonteiro** [comment]
> Fala galera, tudo bem com vocês?
> Eu trabalho a madrugada toda, então se quiserem podemos fazer uma call a qualquer dia a noite e testarmos no meu pc.

Man, conversei com o @jacobaraujo7 pelo grupo da Flutterando no Telegram e o problema aparentemente é com o nosso SO, o Windows 7. :´(

**Comment by ThiagoFTelles** [comment]
> > Fala galera, tudo bem com vocês?
> > Eu trabalho a madrugada toda, então se quiserem podemos fazer uma call a qualquer dia a noite e testarmos no meu pc.
> 
> Man, conversei com o @jacobaraujo7 pelo grupo da Flutterando no Telegram e o problema aparentemente é com o nosso SO, o Windows 7. :´(

Pois é, o @Bwolfs2 falou a mesma coisa comigo.
Se acharem cabível, podem fechar a issue...
