### ISSUE TITLE
Gerar Interfaces através do Slidy

### ISSUE THREAD

**Issue by toshiossada** [Flutterando/slidy#124]
poderia ter um slidy generate interface bla_repository

ou se nao na hora de criar um repository / interface vc coloca um argumento como
slidy g r modules/home/repositories/bla -interface
dai ele criaria além do bla_repository.dart uma pasta com nome "interfaces" e dentro dela o bla_repositoy_interface.dart
mesma coisa para os services
slidy g s modules/home/services/bla -interface

**Comment by jacobaraujo7** [comment]
Talvez seria melhor uma flag para criação de interface quando fosse criado um Repository ou service. O que acha?

**Comment by gabuldev** [comment]
Uma flag ficaria ótimo

**Comment by gabuldev** [comment]
Slidy g repository login -i (interface) ou -a (abstract)

**Comment by toshiossada** [comment]
é estava pensando na flag, ficaria otimo
