### ISSUE TITLE
Slidy retornando "ERROR: The lib folder must be empty" mesmo com a pasta vazia

### ISSUE THREAD

**Issue by JoaoWitorFelipe** [Flutterando/slidy#127]
Estou utilizando o Linux (Mint) após dar "slidy upgrade", eu criei uma pasta vazia, rodei o comando "flutter create .", apaguei os arquivos dentro da pasta lib e teste e depois rodei "slidy start" e me retornou a mensagem "ERROR: The lib folder must be empty". 
Consegui criar meu projeto após rodar "slidy create myproject", rodou tudo normalmente.

Versão do slidy: "Slidy version: 2.0.0+1"

**Comment by JoaoWitorFelipe** [comment]
Olá, acabei gravando um vídeo :P (espero que fique mais claro e também para verificar se não fiz nada de errado), segue o vídeo anexado :D

[empty_folder.mp4.zip](https://github.com/Flutterando/slidy/files/4761847/empty_folder.mp4.zip)

![slidy-version-empty-folder](https://user-images.githubusercontent.com/42946342/84330790-bc246a00-ab5e-11ea-810a-c8a3b37e3e52.png)

**Comment by jacobaraujo7** [comment]
CORRIGIDO!
