### ISSUE TITLE
[Atualizar o comando create] Erro nos imports dos arquivos de teste ao gerar modulo

### ISSUE THREAD

**Issue by LucazzP** [Flutterando/slidy#132]
Quando gera, ele cria com os imports padrões e estes dois:
```
import 'package:mobx_slidy_example/mobx_slidy_example/app/app_controller.dart';
import 'package:mobx_slidy_example/mobx_slidy_example/app/app_module.dart';
```

Porém o correto é dessa forma, se não dá erro:
```
import 'package:mobx_slidy_example/app/app_controller.dart';
import 'package:mobx_slidy_example/app/app_module.dart';
```

**Comment by Bwolfs2** [comment]
Qual versao do Slidy?

**Comment by LucazzP** [comment]
No 2.0.0, só que isso só aconteceu quando dei `slidy create`, depois quando gero separado, não ocorre

**Comment by ivanwhm** [comment]
Mesmo problema aqui. Usando a versão 2.0.0+1

Criado

`
import 'package:tobby/tobby/app/app_controller.dart';
import 'package:tobby/tobby/app/app_module.dart';
`

Correto seria

`
import 'package:tobby/app/app_controller.dart';
import 'package:tobby/app/app_module.dart';
`

**Comment by toshiossada** [comment]
agora o slidy esta fazendo import via referencia, acredito que não havera mais este problema
