### ISSUE TITLE
[Bug Dart 2.8]  ERROR: No valid project found in this folder.

### ISSUE THREAD

**Issue by projectn3xt** [Flutterando/slidy#133]
Slidy version: 2.0.0+1

O comando slidy g m modules/xxxx -c esta gerando o erro 
ERROR: No valid project found in this folder.

o comando slidy create não está criando o projeto, é como se tudo não funcionasse

**Comment by Bwolfs2** [comment]
Isso pelo que constatamos no Discord mais cedo é um problema na versao do Dart 2.8

**Comment by Bwolfs2** [comment]
@projectn3xt  consegue ver se ainda continua com esse Bug? Pois nao consegui simular aqui na minha maquina

**Comment by projectn3xt** [comment]
> @projectn3xt consegue ver se ainda continua com esse Bug? Pois nao consegui simular aqui na minha maquina

A minha versão do dart agora é a 2.8.2 e não tive mais esse problema
