### ISSUE TITLE
Melhoria no create

### ISSUE THREAD

**Issue by keldju** [Flutterando/slidy#136]
As dependencias _hive_ e _pathProvider_ podeiram vir como padrão no create com opção de não usar (ou trocar pro _sharedPreferences_) com um service já iniciado com box com o nome do projeto na pasta shared/services

```
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart' as path_provider;

class StorageService extends Disposable {
  Completer<Box> completer = Completer<Box>();

  StorageService() {
    _initDb();
  }

  _initDb() async {
    final directory = await path_provider.getApplicationDocumentsDirectory();
    Hive.init(directory.path);
    final box = await Hive.openBox('<NomeDoProjeto>');
    if (!completer.isCompleted) completer.complete(box);
  }
}
```

**Comment by jacobaraujo7** [comment]
é uma ótima ideia,
Estamos trabalhando em schematics, que serão alguns templates mais elaborados para esse tipo de feature.
Obrigado!
