### ISSUE TITLE
Bug: Creating project fails to generate needed code

### ISSUE THREAD

**Issue by david-shortman** [Flutterando/slidy#138]
Steps to reproduce:

- Create a new project with `slidy create myproject`
- Run `flutter pub get`
- Run `flutter run -d {device_id}`

Expected result
- The app runs

Actual result
```bash
Compiler message:
lib/app/app_controller.dart:3:6: Error: Error when reading 'lib/app/app_controller.g.dart': No such file or directory
part 'app_controller.g.dart';
```

Additional information:
![Screen Shot 2020-04-20 at 7 16 27 PM](https://user-images.githubusercontent.com/25187726/79808321-76f07280-833b-11ea-8a4a-0b193fbe2f89.png)

**Comment by keldju** [comment]
flutter pub run build_runner build

**Comment by david-shortman** [comment]
Should that be added to the README? Or is that a part of flutter_modular that I missed?

**Comment by LeonardoRosaa** [comment]
No, is that a part of MobX to reactive state-managements.
