### ISSUE TITLE
Criar pastas para "padrões"  específicos

### ISSUE THREAD

**Issue by thiagobrunoms** [Flutterando/slidy#139]
Seria interessante se o slidy tivesse alguma flag pra criar a estrutura de pasta de "arquiteturas" específicas. Por exemplo, 

Pra seguir o Clean Architecture: 

slidy generate module modules/login --clean_architecture 

Já criaria as pastas:

modules
....../login/
............/data/
................../datasources
................../models
................../repositories
............/domain/
................../entities
................../repositories
................../usecases
............/presentation
................../widgets
................../pages
                    ....

**Comment by WilliamCunhaCardoso** [comment]
Acredito que uma issue para esse padrão específico deveria ser aberta.

eu concordo com ela

**Comment by jacobaraujo7** [comment]
é uma excelente ideia!
Estarei olhando pra ela!

**Comment by jacobaraujo7** [comment]
Teremos a função de templates em breve. Obrigado
