### ISSUE TITLE
Bug when generating controller that contains `-` in your file name

### ISSUE THREAD

**Issue by LeonardoRosaa** [Flutterando/slidy#156]
Hi!! First of all, thanks for project.

I think a found a bug that, when by creating a controller per example that contains `-` in your file name, happens this the below: 

command used: `slidy g c modules/home/test-controller`.

<img width="803" alt="Captura de Tela 2020-05-31 às 09 50 31" src="https://user-images.githubusercontent.com/43169851/83352943-74633e80-a325-11ea-8f41-17e1564d703a.png">

**Comment by Bwolfs2** [comment]
O Padrão adotado é Underline(_) que é o Padrão do Dart =/
