### ISSUE TITLE
Opção -c no comando create

### ISSUE THREAD

**Issue by vonmecheln** [Flutterando/slidy#16]
Poderia ser passado o argumento -c para o comando start ao ser criado o projeto inteiro.

https://github.com/Flutterando/slidy/blob/36d5adef0674189dc384eb8a6c9ee0e87baf7ffa/lib/src/modules/create.dart#L26

**Comment by jacobaraujo7** [comment]
estamos otimizando o -c para ser padrão no projeto, precisamos apenas definir o fluxo de rotas nomeadas
