### ISSUE TITLE
Bug: não é possível selecionar Provider e State Management

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/slidy#163]
Não consigo usar o `slidy` no Linux para selecionar tanto o Provider como o State Management. O slidy pergunta qual a opção desejada, mas não consigo me mover com as setinhas, então só consigo criar projetos com as opções default.

![](https://raw.githubusercontent.com/Flutterando/slidy/master/screenshots/choose_provider.PNG)

**Comment by jacobaraujo7** [comment]
Criei uma maquina virtual do Linux e funcionou por agora.
Gostaria de ter mais detalhes sobre isso.

**Comment by Ascenio** [comment]
Em qual distro você testou? Eu mudei até de terminal aqui e o problema persiste.

**Comment by Ascenio** [comment]
Consegui resolver. É necessário atualizar o PATH **após** ter instalado o slidy. Seria bom reforçar isso na documentação.
```bash
pub global activate slidy
export PATH="$PATH:$HOME/.pub-cache/bin"
```
