### ISSUE TITLE
Bug no teste CardWidget

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/slidy#164]
O teste "CardWidget has message" está apresentando erro. Aqui está [stacktrace](https://pastebin.com/EN4T2cwu) completo.
![Erro](https://imgur.com/L74iMuU.png)

**Comment by jacobaraujo7** [comment]
Acredito que esse problema não seja relacionado com o Slidy.
Mas sinta-se a vontade para criar uma issue no Repositório do Modular para invertigarmos isso :)
