### ISSUE TITLE
ERROR: Module not found

### ISSUE THREAD

**Issue by rodrigossimoes** [Flutterando/slidy#17]
Instalei o Slidy version: 0.2.0 e executei o comando:

`slidy start`

Foi criado automaticamente os diretórios: 

APP
| - app_bloc.dart
| - app_module.dart
| - app_widget.dart

HOME
| - home_bloc.dart
| - home_module.dart
| - home_page.dart

Após executei o comando para criar um bloc:

`slidy g b shared/blocs/usuario`

E retornou o seguinte resultado:

`Creating bloc...`
`File lib/src/shared/blocs/usuario_bloc.dart created`
`ERROR: Module not found`

Percebi, que através de um vídeo do tutorial do @jacobaraujo7 os arquivos do APP estavam na raiz do src. Após mover os arquivos para a raiz, o comando foi executado com sucesso.

`Creating bloc...`
`File lib/src/shared/blocs/usuario_bloc.dart created`
`SUCCESS: bloc created`
`SUCCESS: lib/src/app_module.dart modified`

**Comment by jacobaraujo7** [comment]
OBRIGADO.
Corrigido na versão 0.2.1
