### ISSUE TITLE
Referencia de pasta na instalação

### ISSUE THREAD

**Issue by FagundesFurtado** [Flutterando/slidy#171]
Estou usando o Slidy para inicializar um projeto com o modular e mobx. Na instalação retorna que não encontrou o 'pubspec.yaml'.

 Fazendo alguns testes, percebi que isso ocorre para a inserção da tag scripts.
Se eu crio um pubspec.yaml na pasta atual, e executo `slidy create app`, ele insere a tag scripts no arquivo da pasta atual, e não no yaml do projeto

```
Slidy 2.1.1
Dart 2.8.4
Ubuntu 20.04
```

**Comment by toshiossada** [comment]
Hmm  verei isso

**Comment by FagundesFurtado** [comment]
Já publiquei uma PR resolvendo esse problema

**Comment by toshiossada** [comment]
corrigi tb ,kkk

**Comment by toshiossada** [comment]
https://github.com/Flutterando/slidy/pull/176
