### ISSUE TITLE
Corrigir tradução de "TesteFile" para "TestFile"

### ISSUE THREAD

**Issue by isorensen** [Flutterando/slidy#174]
# Summary

Fix translation to English of console message when creating a test file.

## What is happening

SUCCESS: lib/app/app/modules/loan/loan_module.dart modified
File test test/app/app/modules/loan/loan_controller_test.dart created
 **_TesteFile_**: 'lib/app/app/modules/loan/loan_module.dart'

## What should happen

SUCCESS: lib/app/app/modules/loan/loan_module.dart modified
File test test/app/app/modules/loan/loan_controller_test.dart created
 **_TestFile_**: 'lib/app/app/modules/loan/loan_module.dart'

**Comment by isorensen** [comment]
PR já submetido com correção, aguardando análise/aprovação: https://github.com/Flutterando/slidy/pull/173

**Comment by jacobaraujo7** [comment]
Thanks!!!
