### ISSUE TITLE
Feature: atualizar as dependências

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/slidy#179]
Seria interessante ter um comando para atualizar todas as dependências para suas últimas versões. 
```sh
# Atualizando as `dependencies`
slidy update --all

# Atualizando apenas as `dev_dependencies`
slidy update --all-dev

# Ou ambos
slidy update --both
```

**Comment by Ascenio** [comment]
Obviamente a sintaxe `slidy u` também aceitaria os mesmos parâmetros.

**Comment by toshiossada** [comment]
hmmm interessante verei a respeito

**Comment by toshiossada** [comment]
tem o comando update, poderia agregar nele

**Comment by toshiossada** [comment]
https://github.com/Flutterando/slidy/pull/183 enviado 

no caso  vc usara slidy update -a ou  slidy update -a --dev

**Comment by Ascenio** [comment]
Bom trabalho :smiley:
