### ISSUE TITLE
Erro ao 'descomentar' orientacao padrao no pubspec.yaml com vars & scripts gerados no create

### ISSUE THREAD

**Issue by keldju** [Flutterando/slidy#182]
Com a ultima versão do slidy (2.1.2+2) ao criar um novo projeto, adiciona-se variáveis e scripts ao pubspec.yaml  :tada: 
Porém ao adicionar caminho para imagens no pubspec.yaml, descomentando a "orientação" padrão, ocorre o seguinte erro, provavelmente causado pela 'identação' no arquivo;

(sugestão)
Adicionar as variáveis e scripts ao final do arquivo em pubspec.yaml

**Comment by toshiossada** [comment]
PR aberta para correção da issue https://github.com/Flutterando/slidy/pull/181
