### ISSUE TITLE
compiler error when use flutter_modular

### ISSUE THREAD

**Issue by vergilw** [Flutterando/slidy#188]
i got a compiler error 
`Compiler message:`
`lib/app/bloc/app_bloc.dart:7:7: Error: The superclass, 'Bloc', has no unnamed constructor that takes no arguments.`
`class AppBloc extends Bloc<AppEvent, AppState> {                        `
`      ^            `                                                     
`lib/app/modules/home/bloc/home_bloc.dart:7:7: Error: The superclass, 'Bloc', has no unnamed constructor that takes no arguments.`
`class HomeBloc extends Bloc<HomeEvent, HomeState> {                `     
`      ^                                            `

**Comment by jacobaraujo7** [comment]
Fixed
