### ISSUE TITLE
Named Routes não abre HomeModule

### ISSUE THREAD

**Issue by winstonsec** [Flutterando/slidy#19]
Compiler message:
lib/src/routes/routes.dart:9:40: Error: A value of type 'HomeModule' can't be assigned to a variable of type 'StatefulWidget'.
 - 'HomeModule' is from 'package:mobile/src/home/home_module.dart' ('lib/src/home/home_module.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('file:///D:/dev/env/flutter_sdk/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing the type of the left hand side, or casting the right hand side to 'StatefulWidget'.
    '/home': (BuildContext context) => HomeModule(),
                                       ^
Compiler failed on D:\dev\proj\retomada\mobile\lib\main.dart

**Comment by jacobaraujo7** [comment]
Please, update package bloc_pattern to version 2.3.2
