### ISSUE TITLE
error in slidy localization when string falls to the bottom line

### ISSUE THREAD

**Issue by isorensen** [Flutterando/slidy#190]
# Summary

When using `slidy localization` to automate strings localization with more than 80 (or max column lines) characters does not work.

## Screenshots

![Captura de Tela 2020-07-29 às 10 34 39](https://user-images.githubusercontent.com/3399976/88807174-c4287f80-d187-11ea-8628-b62aaa306bd9.png)

When trying to use `slidy localization` this does not work, because when you save the file, auto-format makes the line falls to the line below:  

![Captura de Tela 2020-07-29 às 10 34 16](https://user-images.githubusercontent.com/3399976/88807267-e7ebc580-d187-11ea-87a1-97b206dec1e3.png)

And then, `slidy localization` does not work:  

```
0 items to add.
Items added successful.
Replacing i18n comments
```

**Comment by isorensen** [comment]
```
slidy --version

███████╗██╗     ██╗██████╗ ██╗   ██╗     ██████╗██╗     ██╗
██╔════╝██║     ██║██╔══██╗╚██╗ ██╔╝    ██╔════╝██║     ██║
███████╗██║     ██║██║  ██║ ╚████╔╝     ██║     ██║     ██║
╚════██║██║     ██║██║  ██║  ╚██╔╝      ██║     ██║     ██║
███████║███████╗██║██████╔╝   ██║       ╚██████╗███████╗██║
╚══════╝╚══════╝╚═╝╚═════╝    ╚═╝        ╚═════╝╚══════╝╚═╝                                             

CLI package manager and template for Flutter

Slidy version: 2.1.2+2
```

**Comment by jacobaraujo7** [comment]
Slidy no have support to localization actually. Sorry.
