### ISSUE TITLE
BLoC 6.0 and Cubit

### ISSUE THREAD

**Issue by fernando-s97** [Flutterando/slidy#193]
What are chances to add support for Cubit?

**Comment by Bwolfs2** [comment]
Big!!!  We will reestructure all the Slidy and this is on our goal =)

**Comment by fernando-s97** [comment]
Aewsome!

**Comment by danielmessi13** [comment]
Novidades?

**Comment by Bwolfs2** [comment]
Work on it :C
Trabalhando nisso ainda :C 

@danielmessi13

**Comment by jacobaraujo7** [comment]
ok!
