### ISSUE TITLE
Apos o ultimo update do dart o slidy fecha o console após executar comando

### ISSUE THREAD

**Issue by toshiossada** [Flutterando/slidy#194]
Windows 10
λ flutter doctor -v                                                                                 
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [versÃ£o 10.0.19041.388], locale pt-BR)   
    • Flutter version 1.20.1 at C:\flutter                                                          
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700                         
    • Engine revision c8e3b94853                                                                    
    • Dart version 2.9.0                                                                            
                                                                                                    
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)                    
    • Android SDK at C:\Users\Avell\AppData\Local\Android\Sdk                                       
    • Platform android-29, build-tools 29.0.2                                                       
    • ANDROID_HOME = C:\Users\Avell\AppData\Local\Android\Sdk                                       
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java                          
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                   
    • All Android licenses accepted.                                                                
                                                                                                    
[√] Android Studio (version 3.6)                                                                    
    • Android Studio at C:\Program Files\Android\Android Studio                                     
    • Flutter plugin version 45.1.1                                                                 
    • Dart plugin version 192.7761                                                                  
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                   
                                                                                                    
[√] VS Code (version 1.47.3)                                                                        
    • VS Code at C:\Users\Avell\AppData\Local\Programs\Microsoft VS Code                            
    • Flutter extension version 3.13.2                                                              
                                                                                                    
[!] Connected device                                                                                
    ! No devices available                                                                          
                                                                                                    
! Doctor found issues in 1 category.                                                    

![erro](https://user-images.githubusercontent.com/2637049/89744716-0013ec80-da86-11ea-8fa2-01bdaa832fdb.gif)

**Comment by BerkSpar** [comment]
A issue #191 pode ter algo em comum com o erro.

**Comment by DeveJonatas** [comment]
O mesmo está acontecendo comigo.

**Comment by DeveJonatas** [comment]
Olá,
na minha maquina resolvi fazendo o seguinte:
Executei `choco upgrade dart-sdk`
Deletei a pasta `Pub\Cache\global_packages\slidy` e executei `pub global activate slidy` novamente.

**Comment by WeslleyFratini** [comment]
@DeveJonatas foi de grande ajuda, valeuu!

**Comment by Bwolfs2** [comment]
@toshiossada a dica do @DeveJonatas resolveu ai pra voce tambem, ou o problema persiste mesmo assim?

**Comment by toshiossada** [comment]
@Bwolfs2 não sei oq fez funcionar, mas agora está normal

**Comment by Bwolfs2** [comment]
Vou fechar aqui, qualquer coisa soh reabrir ou abrir um novo =D
