### ISSUE TITLE
depends on build_runner >=1.10.2

### ISSUE THREAD

**Issue by gabrieloctavio** [Flutterando/slidy#195]
Bom dia, pessoal!

Estou tendo um problema ao utilizar o slidy com mobx.

Esse é o erro que aparece:
The current Dart SDK version is 2.9.0.

Because APP_NAME depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.
pub get failed (1; Because APP_NAMEdepends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.)
exit code 1

**Comment by toshiossada** [comment]
esse é um problema do build_runner, eu fiz um downgrade para o 1.10.1
teve um brakiing change 
https://github.com/dart-lang/sdk/issues/42887
![image](https://user-images.githubusercontent.com/2637049/90030521-869d1980-dc92-11ea-9678-63cc9e430f6f.png)

**Comment by toshiossada** [comment]
Pelo que entendi o build_runner depende do dart 2.10 que esta em prerelease, no canal dev,

**Comment by gabrieloctavio** [comment]
Fiz o downgrade do build_runner e deu certo. Obrigado.
