### ISSUE TITLE
Bug no slidy generate

### ISSUE THREAD

**Issue by wendellrocha** [Flutterando/slidy#202]
Após atualizar pra versão 2.0.0+1 ao usar o slidy g ele não resolve a variável no bind do module.

![Screenshot_20200827_155041](https://user-images.githubusercontent.com/20341692/91482830-1343fc00-e87d-11ea-8650-3545b0b5bdb3.png)

**Comment by leonard95GT** [comment]
Eu tb tive o mesmo problema. E no momento da criação, ele duplicou alguns nomes de pastas no path de alguns imports. 
![Captura de Tela 2020-09-12 às 23 24 04](https://user-images.githubusercontent.com/46646057/93008765-10205f80-f54f-11ea-883d-6c71c09953fd.png)

**Comment by leonard95GT** [comment]
Consegui arrumar, fazendo o bind dentro do app_module...e aí foi só alegria hahah


![Captura de Tela 2020-09-12 às 23 43 43](https://user-images.githubusercontent.com/46646057/93009002-d7ce5080-f551-11ea-8f22-b8763239515f.png)

**Comment by RenatoCesarF** [comment]
Essa issue foi fechada? Ninguem conseguiu resolver?

**Comment by wendellrocha** [comment]
> Essa issue foi fechada? Ninguem conseguiu resolver?

Até então o bug persiste.

**Comment by RenatoCesarF** [comment]
Se você fizer na mão ele funciona, ou seja, em vez de usar o slidy vc apenas digita as linhas sozinho e ele funciona

**Comment by jacobaraujo7** [comment]
fixed
