### ISSUE TITLE
Can't load Kernel binary: Invalid SDK hash

### ISSUE THREAD

**Issue by casenvi** [Flutterando/slidy#204]
* **Operational System**: 
  WIndows
* **How to repeat the beheavior**:
  1. Install slidy follow the README instructions
  2. Run the command `slidy --version`
  3. Script print after version `Can't load Kernel binary: Invalid SDK hash`
* **Severity**:
  non-blocking

**Comment by casenvi** [comment]
This issue have the dart version in its origin. 

To solve this issue we can:

1. Download Dart version 2.9.2 in https://dart.dev/tools/sdk/archive
2. Unzip in some directory, ex. c:\tools\dart-sdk
3. Add the directory\bin (ex.  c:\tools\dart-sdk\bin) to path environment before flutter entry.
4. Restart prompt to use new path environment

**Comment by claudneysessa** [comment]
![image](https://user-images.githubusercontent.com/12506432/92360888-eafd9e00-f0c3-11ea-85d3-d1d7dccfde32.png)

Olá! Tenho o Dart atualizado para a ultima versão, tenho minha maquina frequentemente atualizada, utilizo o chocolatey para manter tudo funcionando e ainda tenho a mensagem ao utilizar o Slidy, como será que posso resolver?

**Comment by claudneysessa** [comment]
![image](https://user-images.githubusercontent.com/12506432/92361071-3adc6500-f0c4-11ea-902d-c32f7f3b2bc6.png)

**Comment by abraaolevi** [comment]
@claudneysessa Eu já tive um problema parecido, mas com outra biblioteca. 

O que me ajudou foi essa _issue_ https://github.com/dart-lang/pub/issues/2593. Basicamente é rodar o _activate_: `pub global activate <package>`.

No README do projeto tem uma seção que talvez possa ajudar: https://github.com/Flutterando/slidy#common-errors

---

I had the same problem with another library. This issue (https://github.com/dart-lang/pub/issues/2593) helped me a lot. Basically, I ran `pub global activate <package>`.

At README this project there is a [section about common errors](https://github.com/Flutterando/slidy#common-errors), maybe can help you.

**Comment by claudneysessa** [comment]
resolvido!

pub global deactivate slidy
pub global activate slidy

**Comment by eduardotq** [comment]
Mesmo problema aqui. Segui os passos da documentação, mas ao rodar o slidy --version retorna

`Can't load Kernel binary: Invalid kernel binary format version.`

Same problem here. I followed the steps in the documentation, but when running the slidy - version returns

`Can't load Kernel binary: Invalid kernel binary format version.`

**Comment by abraaolevi** [comment]
@eduardotq esse parece ser um erro diferente, talvez essa [_issue_](https://github.com/flutter/flutter/issues/21810#issuecomment-546514043) no repo do flutter possa lhe ajudar.

---

Its look a different error, maybe this [_issue_](https://github.com/flutter/flutter/issues/21810#issuecomment-546514043) can help you

**Comment by hiuryanderson** [comment]
Eu apanhei bastante para descobrir que tinha instalado o Dart na minha maquina com um instalador Windows e o Flutter a partir da versão 1.20 esta vindo com o dart completo, não sendo mais necessário instalar o dart a parte. Ficou uma confusão de dart na maquina e ele estava executando a versão antiga e com isso não executa o slidy.

Para saber se esse é o seu problema tenta executar o slidy no flutter 

Foi só desinstalar o Dart do Windows que consegui atualizar e executar o slidy.

**Comment by bcocheto** [comment]
> Eu apanhei bastante para descobrir que tinha instalado o Dart na minha maquina com um instalador Windows e o Flutter a partir da versão 1.20 esta vindo com o dart completo, não sendo mais necessário instalar o dart a parte. Ficou uma confusão de dart na maquina e ele estava executando a versão antiga e com isso não executa o slidy.
> 
> Para saber se esse é o seu problema tenta executar o slidy no flutter
> 
> Foi só desinstalar o Dart do Windows que consegui atualizar e executar o slidy.

Uso a versão dev do flutter, tentei fazer o que você fez, e agora nem acha o pub haha mesmo colocando na path

**Comment by augusto3691** [comment]
Eu consegui resolver aqui galera:

Como o @hiuryanderson disse, de fato o Flutter na versão 1.20 introduziu o dart completo, então basicamente vcs precisam desinstalar do ambiente global e do flutter:

```
flutter pub global deactivate slidy
pub global deactivate slidy
```

e depois instalar apenas no flutter
```
flutter pub global activate slidy
```

aqui rolou ;)

**Comment by jodaias** [comment]
@augusto3691 aqui deu certo pra mim... valeu

**Comment by mthss** [comment]
Acabei de atualizar meu flutter e tive o mesmo erro.
Estou passando para avisar que a solução do @augusto3691 no dia 12/11 solucionou meu problema.
Valeuuuu

**Comment by RaulDuque** [comment]
alguem pode me ajudar ? estou tendo esse erro com o slidy 
![image](https://user-images.githubusercontent.com/80526632/121377333-a0da6f00-c918-11eb-885c-8c0325cc0fb2.png)

**Comment by mathsilva-dev** [comment]
> alguem pode me ajudar ? estou tendo esse erro com o slidy
> ![image](https://user-images.githubusercontent.com/80526632/121377333-a0da6f00-c918-11eb-885c-8c0325cc0fb2.png)

Qual versão do seu flutter?

**Comment by giliard-ss** [comment]
> resolvido!
> 
> pub global deactivate slidy
> pub global activate slidy

Perfect! Worked for me.
