### ISSUE TITLE
Os Scripts de execução do slidy para o Mobx  não estão funcionando automaticamente 

### ISSUE THREAD

**Issue by rodrigocc** [Flutterando/slidy#210]
Pessoal quando eu utilizo esses scripts do Slidy referente ao Mobx eles não estão sendo executados de maneira automática . Ele só exibe o comando no terminal como um print .

Esses são os comandos que estão com o mesmo comportamento:

scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

Então sempre que uso esses comandos eu preciso ficar copiando e colando ctrl c + v para que ele funcione .
![SlidyScripts](https://user-images.githubusercontent.com/20406478/94698161-680ce380-030f-11eb-9a21-745a4c33c544.png)

Essas são as versões do Flutter , Slidy , Dart e OS da minha máquina

Flutter 1.20.4
Channel Stable
Dart SDK version: 2.11.0-176.0.dev 
Slidy version: 2.2.1
Sistema Operacional : Linux Mint 19.3 Tricia.

**Comment by alethadeu** [comment]
Oi Rodrigo, estava com esse problema também, o que fiz foi rodar o comando fora do slidy, então percebi que havia um erro no pubspec. Talvez possa ser isso contigo...

**Comment by rodrigocc** [comment]
Eu troquei o meu OS do Mint Para o Zorin OS , depois da mudanca funcionou normalmente.

**Comment by Bwolfs2** [comment]
Posso fechar @rodrigocc ?

**Comment by rodrigocc** [comment]
Pode sim =)
