### ISSUE TITLE
Bloc error

### ISSUE THREAD

**Issue by acamenhas** [Flutterando/slidy#212]
Boas,

Criei um projecto com bloc e quando foi actualizar os packages deu o seguinte erro:

```
Error on line 27, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷

27 │   bloc: ^6.1.0

   │   ^^^^

   ╵
pub get failed (65;    ╵)
exit code 65
```

Obrigado

**Comment by Bwolfs2** [comment]
Consegue postar o pubspec.yaml completo? Fico no Aguardo

**Comment by acamenhas** [comment]
Boas, voltei a criar um projecto com bloc e já não deu esse erro.
A única questão é que nos ficheiros _bloc.dart dá um erro de falta de argumento:

![bloc](https://user-images.githubusercontent.com/14015712/100516778-14d3d780-317e-11eb-9ddc-6765a6fcee58.png)


Obrigado!

**Comment by Bwolfs2** [comment]
O Bloc atualizou e eu nao terminei de atualizar o package :C
The Bloc has been updated and i have't finished updating Slidy :C

**Comment by jacobaraujo7** [comment]
fixed
