### ISSUE TITLE
slidy create projectest error: Undefined name '$AppController' 

### ISSUE THREAD

**Issue by hermesalvesbr** [Flutterando/slidy#215]
Hi there,

I'm trying to start a new project using: `slidy create projectteste`, but slidy makes a wrong pubspec.yaml:

https://user-images.githubusercontent.com/379850/105056714-487eff80-5a53-11eb-97c2-4a7aa89a7383.mov

After this, i changed the pubspec.yaml and fix the wrong line, but appear a new error: 

https://user-images.githubusercontent.com/379850/105057127-aca1c380-5a53-11eb-83df-e7941dbf1c02.mov

After run `flutter pub run build_runner build --delete-conflicting-outputs` and `clean` the problem persist.

![Captura de Tela 2021-01-19 às 12 36 35](https://user-images.githubusercontent.com/379850/105057469-073b1f80-5a54-11eb-8d8f-17e75d252469.png)

How can i fix this error in line 9 of home_module.dart?

**Comment by Bwolfs2** [comment]
try run flutter ```pub run build_runner build```

**Comment by hermesalvesbr** [comment]
Didn't work @Bwolfs2 

![Captura de Tela 2021-01-19 às 13 30 55](https://user-images.githubusercontent.com/379850/105063525-96e3cc80-5a5a-11eb-881e-4a1eb4e16ab2.png)

:(

> Undefined name '$HomeController'.
Try correcting the name to one that is defined, or defining the name.dartundefined_identifier

**Comment by Bwolfs2** [comment]
I forgot the FLUTTER is:  ```flutter pub run build_runner build```

**Comment by hermesalvesbr** [comment]
Hi again,

I made a completely new install on windows, and i got the same errors.  I was in mac, and now in windows and i got the same erro. I think the slidy has a bug on create. And the mobx another one.

Please check the printscreen, maybe i need to change the flutter version or slidy version?

![image](https://user-images.githubusercontent.com/379850/105138759-1c579300-5ad4-11eb-8bf0-c35c3442cedb.png)

Thanks for you patience and attention ;-)

**Comment by romaque** [comment]
Hi, i have the same problem here too.

**Comment by RodrigoRivasF** [comment]
I just put the previous code and it worked:

`Bind((i) => HomeController()),`

**Comment by hermesalvesbr** [comment]
It's really necessary change code generated by slidy?

**Comment by icfilho** [comment]
> flutter pub run build_runner build

Not works.

**Comment by LeonardoRosaa** [comment]
@hermesalvesbr what is version your `modular codegen`??

**Comment by hermesalvesbr** [comment]
modular_codegen: ^2.1.0

**Comment by joaoarmando** [comment]
Same here.

**Comment by GvictorFranca** [comment]
Try to change flutter  channel for stable and upgrade it

**Comment by chnmelo** [comment]
Same here.

**Comment by GvictorFranca** [comment]
Change $HomeController to Bind((i) => HomeController()), works for me
