### ISSUE TITLE
HasuraConnect opção

### ISSUE THREAD

**Issue by acamenhas** [Flutterando/slidy#216]
Era bom que tivéssemos a opção de criar o repository com HasuraConnect e não só com o DIO.
Cada vez que crio um módulo tenho que ir alterar os repositórios à mão.
E como o HasuraConnect é um projecto da Flutterando, acho que faria sentido haver uma flag de forma a promover essa integração.

Obrigado!

**Comment by LeonardoRosaa** [comment]
> Era bom que tivéssemos a opção de criar o repository com HasuraConnect e não só com o DIO.
> Cada vez que crio um módulo tenho que ir alterar os repositórios à mão.
> E como o HasuraConnect é um projecto da Flutterando, acho que faria sentido haver uma flag de forma a promover essa integração.
> 
> Obrigado!

Eu iniciei essa implementação, estou quase finalizando... mas estou um pouco ocupado no momento.

**Comment by acamenhas** [comment]
É isso mesmo @LeonardoRosaa 
Quando houver novidades avisa.
Obrigado!

**Comment by jacobaraujo7** [comment]
Vamos ter uma opcao de templates customizados para esse tipo de trabalho.
