### ISSUE TITLE
Slidy breaks pubspec dependencies

### ISSUE THREAD

**Issue by RenatoCesarF** [Flutterando/slidy#222]
I'm trying to add slidy and mobx to my project but after create the flutter project, use pub get, install slidy and run slidy start
the `flutter pub get` return me error

`
Because modular_codegen >=2.0.0+1 <3.0.0-nullsafety.1 depends on analyzer >=0.38.5 <0.41.0 and mockito >=5.0.0 depends on analyzer ^1.0.0, modular_codegen >=2.0.0+1 <3.0.0-nullsafety.1 is incompatible with mockito >=5.0.0.
So, because aaa depends on both mockito ^5.0.0 and modular_codegen ^2.1.0, version solving failed.
Running "flutter pub get" in aaa...                                     
pub get failed (1; So, because aaa depends on both mockito ^5.0.0 and modular_codegen ^2.1.0, version solving failed.)
`

Maybe the slidy start is breaking my pubspac.yalm. Anyone have a way to fix it?

**Comment by Bwolfs2** [comment]
U have to do 2 fix: 
1- Change mockito 5.0.0 to mockito 4.1.4
2- Change modular_codegen ^2.1.0 to mockito ^2.0.1

**Comment by DQ318** [comment]
@Bwolfs2 

Hi man!

Your solution did not work for me because I continue to receive the same error, now, directed to the package _"flutter_modular_annotations"_.

```
The current Dart SDK version is 2.10.5.                                 
                                                                        
Because modular_codegen >=2.1.0 <3.0.0-nullsafety.1 depends on flutter_modular_annotations >=0.0.2 which requires SDK version >=2.12.0-0 <3.0.0, modular_codegen >=2.1.0 <3.0.0-nullsafety.1 is forbidden.
So, because project depends on modular_codegen ^2.1.0, version solving failed.
Running "flutter pub get" in project...                                 
pub get failed (1; So, because project depends on modular_codegen ^2.1.0, version solving failed.)
```
My environment is up to date and I use Ubuntu 18.04:

```
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (6 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```
When I change to previous versions, the "pub get" until it works but it generates a series of other problems.

**Comment by RenatoCesarF** [comment]
Now he doesn't recognize the controllers, but there is a issue already register for that
