### ISSUE TITLE
Sugestão: Criar pasta "pages" para organizar melhor as páginas

### ISSUE THREAD

**Issue by wemersonrv** [Flutterando/slidy#23]
Bom dia. 

Gostaria de sugerir que se criasse uma pasta **pages** na src para conter as páginas... Percebi que um projeto grande com muitas páginas vai fazer a `src` ficar enorme, e teremos muitas páginas misturadas com outras e pode ficar verboso e se já criarmos um projeto com uma pasta para organizar as páginas seria interessante.

**Comment by jacobaraujo7** [comment]
Atualizado na versão 1.0.0
