### ISSUE TITLE
Slidy CLI trava no cmd do windows

### ISSUE THREAD

**Issue by DawidOliveira** [Flutterando/slidy#231]
## Description
Ao executar o slidy start e selecionar a gerencia de estado o cmd mostra a criação de 3 arquivos e simplesmente trava

**Comment by brotoo25** [comment]
@DawidOliveira Testando com um projeto recém criado ```flutter create new_project``` funciona tranquilo.

**Comment by DawidOliveira** [comment]
@brotoo25 interessante, vou formatar meu pc então para verificar se ainda persiste o problema
