### ISSUE TITLE
--help doesn't return arguments for slidy g m ./modules/home

### ISSUE THREAD

**Issue by evandrmb** [Flutterando/slidy#237]
In previous versions of slidy if the user type `-h` or `--help` after a command like that: `slidy g m ./modules/home` it was shown the possible arguments to pass. In version `3.0.0` all it's show is:
![image](https://user-images.githubusercontent.com/47798920/111329348-d2aba480-864d-11eb-8415-4f6b9fdb876b.png)

Also if I try the -c argument wich previous stand for complete, generating module with pages and controller it is returned
![image](https://user-images.githubusercontent.com/47798920/111329497-ef47dc80-864d-11eb-9585-67b7bfe83b10.png)

**Comment by marcuslindemannrohden** [comment]
going through the same issue. **slidy g m 'path' -c** does not recognize the tag **'-c'**

**Comment by jacobaraujo7** [comment]
Hello.
-C today is no longer supported as slidy is now agnostic to state management, so we would not be able to say which is the default state management.
