### ISSUE TITLE
Widget template allowing null to the Key

### ISSUE THREAD

**Issue by fabiomotta0311** [Flutterando/slidy#238]
The template widget created by slidy generate (below example) face error because the new version null safe did not allow null"key?" 

"slidy generate widget manager/product/widgets/product_detail"

![slidy_widget_tpl_pic](https://user-images.githubusercontent.com/8262930/111363425-ca179600-866e-11eb-90f7-d62b8e6cbcc5.PNG)

just remove the question mark from the model

**Comment by jacobaraujo7** [comment]
It's cause a error in sound nullsafety codes.
So, we had worked up to nullsafety dart versions.
