### ISSUE TITLE
Slidy generate module fails with "file x_module exists"

### ISSUE THREAD

**Issue by raff-run** [Flutterando/slidy#241]
Whenever I try to generate a module, slidy works until the first file is created (x_module.dart), then fails saying the file it just created already exists. I'm trying to migrate my existing project to this new structure, so this is how it looks before I try anything:
![image](https://user-images.githubusercontent.com/44688128/112174233-026e2580-8bd5-11eb-98bd-1bfc54c5a168.png)
And this is what happens when I try to generate a module:

> \>slidy generate module prototype
>SUCCESS: prototype_module created
>ERROR: File prototype_module exists

After the error, the following file is present:
![image](https://user-images.githubusercontent.com/44688128/112174127-ebc7ce80-8bd4-11eb-9ec7-873ede2e2177.png)

This happens regardless of which name/path I use. I tried downgrading to 2.2.1, but it also happens on that version.

These were my installation steps:
1. I added D:\flutter\bin\cache\dart-sdk\bin to PATH so I could use the "pub" command
2. Ran pub global activate slidy, it warned me that %localappdata%\Pub\Cache\bin wasn't in path
2. Added that to PATH because pub global activate installed slidy there
3. Ran slidy generate module prototype

I'm on Windows 10.

**Comment by raff-run** [comment]
Hard to tell since I'm new to this, but it seems that it _**is**_ working correctly (by that I mean it generates the files correctly), the only problem here seems to be that it always runs twice.

**Comment by rodrigofelipejr** [comment]
When you run the `slidy --version` command, are you also displaying this? @raff-run 

![Screenshot_1](https://user-images.githubusercontent.com/8061982/112244745-70930680-8c2e-11eb-961e-41e0ba08ca99.png)

**Comment by raff-run** [comment]
Just tested it and yes, it prints twice.

**Comment by jacobaraujo7** [comment]
Fixed!
