### ISSUE TITLE
[erro] slidy start

### ISSUE THREAD

**Issue by alvaroreis** [Flutterando/slidy#244]
Unhandled exception:
NoSuchMethodError: Class 'String' has no instance method '[]='.
Receiver: "flutter clean"
Tried calling: []=("get", Instance of 'Line')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      PubspecServiceImpl.loadYaml (package:slidy/src/core/services/pubspec_service_impl.dart:45:40)
<asynchronous suspension>
#2      PubspecServiceImpl.add (package:slidy/src/core/services/pubspec_service_impl.dart:100:19)
<asynchronous suspension>
#3      PackageInstalationRepositoryImpl.install (package:slidy/src/modules/package_instalation/infra/repositories/package_instalation_repository.dart:29:22)<asynchronous suspension>
#4      Install.call (package:slidy/src/modules/package_instalation/domain/usecases/install.dart:15:12)
<asynchronous suspension>
#5      StartCommand.run (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/slidy-3.0.2/bin/commands/start_command.dart:127:14)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>

**Comment by Ascenio** [comment]
Você pode mandar uma foto da sua estrutura de pastas, a partir de qual pasta você rodou o comando e o seu pubspec.yaml?

**Comment by JacquesMarques** [comment]
@alvaroreis you are using flutter_launcher_icons package? If yes and you put flutter_icons: declaration on you pubspack,yaml file, this is the cause of your error, remove the flutter_icons:  declaration to another file like flutter_launcher_icons.yaml, and the error is fixed.

**Comment by alvaroreis** [comment]
> 
> 
> @alvaroreis you are using flutter_launcher_icons package? If yes and you put flutter_icons: declaration on you pubspack,yaml file, this is the cause of your error, remove the flutter_icons: declaration to another file like flutter_launcher_icons.yaml, and the error is fixed.

Obrigado, resolveu meu problema.
