### ISSUE TITLE
Cmd commands invoked twice

### ISSUE THREAD

**Issue by rogasciences** [Flutterando/slidy#246]
![image](https://user-images.githubusercontent.com/74883643/113507355-95527c80-9552-11eb-9fbc-3cb7711f1daa.png)

When trying to invoke a command over the terminal in VS Code, slidy commands run twice, making it impossible to work with.

Has anyone encountered that problem?

`environment:
  sdk: ">=2.12.0 <3.0.0"`

`[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at D:\SDKs\flutternullsafe\flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\roini\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\roini\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63

• No issues found`

**Comment by RoySis** [comment]
in the windows file
C:\Users\YOURNAMEUSER\AppData\Local\Pub\Cache\bin\slidy.bat
delete line 14 "pub global run slidy: main% *"

it worked for me :-)

**Comment by izziizzi** [comment]
in the windows file
C:\Users\YOURNAMEUSER\AppData\Local\Pub\Cache\bin\slidy.bat
delete line 14 "pub global run slidy: main% *"

it worked for me :-)

**Comment by RoySis** [comment]
in the windows file
C:\Users\YOURNAMEUSER\AppData\Local\Pub\Cache\bin\slidy.bat
delete line 14 
`pub global run slidy: main% *`

it worked for me :-)

**Comment by jacobaraujo7** [comment]
Check the new version 3.1.0. :)

**Comment by KillerBean** [comment]
> Check the new version 3.1.0. :)

The same behaviour as version 3.0.2

**Comment by roy-xr** [comment]
@jacobaraujo7 Still happening with the new version as well as after applying @izziizzi fix. 

I guess something is wrong with my path setup or so. will check further

**Comment by rogasciences** [comment]
Well I've made some progress 
![image](https://user-images.githubusercontent.com/63206189/116114544-20421500-a6c2-11eb-8e0e-3888bbcd4b90.png)
now it invokes once but says
`'pub' is not recognized as an internal or external command,
operable program or batch file.`

The cause of that is being forced to add `AppData\Roaming\Pub\Cache\bin` to the path variables - Which along with having `C:\src\flutter\bin\cache\dart-sdk\bin` in the path caused the double invocation of the commands . 

I solved this by removing C:\src\flutter\bin\cache\dart-sdk\bin from he path. 

Is any other solution possible? (as it forces me to use "flutter pub" for using dart commands)

Thanks @jacobaraujo7

**Comment by andrewbiller** [comment]
> in the windows file
> C:\Users\YOURNAMEUSER\AppData\Local\Pub\Cache\bin\slidy.bat
> delete line 14 "pub global run slidy: main% *"
> 
> it worked for me :-)

This is the only solution so far for windows (3.2.0).
PATH contains both lines:

```
flutter\bin\cache\dart-sdk\bin
AppData\Roaming\Pub\Cache\bin
```

**Comment by rogasciences** [comment]
Atm only @izziizzi Solution seems to work. Fine for now :)

**Comment by KillerBean** [comment]
Version 3.2.1+1 same thing

**Comment by jacobaraujo7** [comment]
It is a Powershell problem.
Use CMD for this

**Comment by MateusPedrosoSilva** [comment]
> > in the windows file
> > C:\Users\YOURNAMEUSER\AppData\Local\Pub\Cache\bin\slidy.bat
> > delete line 14 "pub global run slidy: main% *"
> > it worked for me :-)
> 
> This is the only solution so far for windows (3.2.0). PATH contains both lines:
> 
> ```
> flutter\bin\cache\dart-sdk\bin
> AppData\Roaming\Pub\Cache\bin
> ```



> in the windows file C:\Users\YOURNAMEUSER\AppData\Local\Pub\Cache\bin\slidy.bat delete line 14 "pub global run slidy: main% *"
> 
> it worked for me :-)

For me it worked!!
