### ISSUE TITLE
Atualização do pacote para nova versão flutter_modular

### ISSUE THREAD

**Issue by JulioCGMC** [Flutterando/slidy#249]
Olá, uso o CLI de vocês à algum tempo e gosto bastante, mas ultimamente ele não tem sido tão proveitoso visto que o flutter_modular, que é o modelo que eu uso, alterou bastante suas nomenclaturas na versão 3.

Gostaria que estivessem atualizando o pacote para poder sujeita-los às novas mudanças.

Obrigado.

**Comment by jacobaraujo7** [comment]
Fix 4.0.1
