### ISSUE TITLE
Slidy gerando store ao invés de gerar controller.

### ISSUE THREAD

**Issue by pedrovmc** [Flutterando/slidy#250]
A nomenclatura store está deprecated no modular, porém o projeto ainda é gerado utilizando essa nomenclatura no comando start e no comando de geração do módulo completo.

**Comment by guiolifer** [comment]
Gostaria de saber também Store/Controller.
Slidy vem alterando bastante nomeclatura, agora o pojeto fica cheio de controller e store.

**Comment by toshiossada** [comment]
nesta issue comento como gosto de utilizar stores e controllers
https://github.com/Flutterando/modular/issues/315#issuecomment-805471557

**Comment by jacobaraujo7** [comment]
fixed
