### ISSUE TITLE
Erros de geração de código ao criar um projeto com mobx

### ISSUE THREAD

**Issue by neyara** [Flutterando/slidy#255]
## Descrição
Quando crio um projeto escolhendo o state manager *mobx*, aparecem os seguintes erros no arquivo **home_page.dart**:

```
Linha 5:
Taget of URI doesn't exist: 'package:slidy_testes/app/modules/home/home_store.dart'
Linha 9:
The parameter 'key' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
```

## Solução
O primeiro problema pode ser contornado substituindo "slidy_testes" pelo nome do pacote do projeto criado como em:
`import 'package:<nome_projeto>/app/modules/home/home_store.dart';`.
Já para o segundo, basta adicionar uma interrogação (?) como em:
`const HomePage({Key ? key, this.title = "Home"}) : super(key: key);`

## Passos para reprodução
- `slidy start`
- state manager: mobx

## Ambiente
- Flutter: 2.2.0
- Dart: 2.13.0
- Slidy: 3.2.2

Criei esta *issue* apenas para caráter informativo, uma vez que os passos da solução já resolvem os problemas.

**Comment by rolimproductions** [comment]
Percebi isso ontem também.

E ao criar o projeto com mobx, não deveria vir também o build_runner nas dev_dependencies?

**Comment by dev-vinicius** [comment]
Acabei de criar um projeto e aconteceu o mesmo comigo.

**Comment by CarvalhoWesley** [comment]
Tentei criar um novo projeto tbm, mas estou tendo problemas com o pubspec.yaml.

> Unhandled exception:
FileSystemException: Cannot open file, path = 'pubspec.yaml' (OS Error: O sistema não pode encontrar o arquivo especificado.

**Comment by itasouza** [comment]
Olá a todos, estou pesquisando uma forma de solucionar um problema usando a versão mais recente do slidy, o tutorial que estou seguindo usa uma versão do slidy 2.2.1, eu tenho a nova versão 3.2.2, seguindo a documentação eu fiz a criação da pasta do meu projeto e após isso usei o comando “slidy start”, antes era “slidy create nome_do_projeto” nas opções escolhi o mobx, ele faz a criação mais tenho um erro:

Unhandled exception:
FileSystemException: Cannot open file, path = 'pubspec.yaml' (OS Error: O sistema n'pub' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by intellitour** [comment]
@neyara Tá na fila o PR com a correção.
@jacobaraujo7

**Comment by itasouza** [comment]
Só para esclarecer, e necessário criar o projeto flutter e após isso dentro da pasta do projeto usar o comando  “slidy start”, desta forma eu não tenho o erro do “pubspec.yaml” mais na versão nova eu tenho a pasta web e a pasta “test” não existe mais, isso da um erro “import 'package:slidy_testes/app/modules/home/home_store.dart';”

**Comment by itasouza** [comment]
> Tentei criar um novo projeto também, mas estou tendo problemas com o pubspec.yaml.
> 
> > Exceção não tratada: 
> > FileSystemException: Não é possível abrir o arquivo, path = 'pubspec.yaml' (Erro do sistema operacional: O sistema não pode encontrar o arquivo especificado.

Olá necessário criar o projeto flutter e após isso dentro da pasta do projeto usar o comando  “slidy start”, desta forma eu não tenho o erro do “pubspec.yaml”
