### ISSUE TITLE
Slidy executa os comandos duas vezes

### ISSUE THREAD

**Issue by JonatasJeremias** [Flutterando/slidy#257]
Todo comando que executo com o Slidy, ele tenta executar duas vezes, fiz o teste executando no powershell e no CMD, o comando  "slidy start" exibe o dialogo para escolher o state manager duas vezes, e o comando "slidy g m ...." também tenta criar o mesmo módulo duas vezes.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/34916878/122467721-3d43e780-cf91-11eb-972f-7e8f8de907cc.gif)

**Comment by joaovvrodrigues** [comment]
Eu estou com o mesmo problema kkkk Deve relativo as variáveis será ?

**Comment by djesusguimaraes** [comment]
![image](https://user-images.githubusercontent.com/66970708/130234641-94570fb0-15ef-46b4-83da-e5e462e93a16.png)

Antes de começar a repetir os comandos ele pede a variável de ambiente do pub.

**Comment by djesusguimaraes** [comment]
Talvez não seja um problema do Slidy. Na imagem abaixo a comparação da duplicação de comandos em função do pub. 
- Com o pub o comando é duplicado. (Terminal lado esquerdo)
- Sem o pub nas variáveis de ambiente o comando apresenta erro. (Terminal lado direito) 


![image](https://user-images.githubusercontent.com/66970708/130242983-57fe9b6f-f994-4c81-8a9f-0ac44083881c.png)

**Comment by RoySis** [comment]
Eu comentei uma solução que deu certo pra mim
#246

**Comment by izziizzi** [comment]
Eu comentei uma solução que deu certo pra mim
#246

**Comment by djesusguimaraes** [comment]
Vlw @izziizzi, resolvido aqui.
