### ISSUE TITLE
slidy: command not found

### ISSUE THREAD

**Issue by claudiooliveira** [Flutterando/slidy#263]
[](url)Estou tentando utilizar o slidy pela primeira vez e não consigo.
Fiz a instalação da seguinte forma:

https://i.ibb.co/6b4GZYV/printz-o.png

(log abaixo caso a imagem seja apagada):
`
$ dart pub global activate slidy
Package slidy is currently active at version 3.2.2+1.
Resolving dependencies...
The package slidy is already activated at newest available version.
To recompile executables, first run `global decativate slidy`.
Installed executable slidy.
Warning: Pub installs executables into C:\Users\claud\AppData\Local\Pub\Cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.
Activated slidy 3.2.2+1.
`

Segue meu flutter doctor:

`$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19043.1165], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

• No issues found!
`

**Comment by xk08** [comment]
**Salve!!**  Pela descrição apresentada em sua imagem (e log) o slidy foi instalado com sucesso mano! 

Para que o slidy seja reconhecido no PowerShell em qualquer local do SO, tu precisa adicionar esse caminho: C:\Users\claud\AppData\Local\Pub\Cache\bin no teu **path** das "variáveis de ambiente" (igual é informado pelo log)

Além disso, pra "rodar/executar" o slidy pela primeira vez em um novo projeto, tu precisa primeiro criar um projeto flutter normal, depois abrir ele, e ai sim executar o slidy, ai vai funcionar.

A documentação do slidy, demonstra esse processo, e também tem video no canal da flutterando ensinando a rodar e utilizar.
https://www.youtube.com/watch?v=cIO1im9sLb0

Espero que te ajude, se funcionar, não esquece de fechar a issue, abraço.

**Comment by keane032** [comment]
mas qual nome coloco na variável de ambiente?
