### ISSUE TITLE
Triple generate with deprecated package

### ISSUE THREAD

**Issue by gbfonseca** [Flutterando/slidy#264]
When generating a triple pattern project, the slide set a dev_dependencies deprecated flutter_modular_test instead of modular test.
Error after run `flutter pub get`.

`Because flutter_modular_test >=1.0.2 depends on flutter_modular ^3.4.1+1 and teste depends on flutter_modular ^4.0.0+6, flutter_modular_test >=1.0.2 is forbidden.
So, because teste depends on flutter_modular_test ^1.0.4, version solving failed.
Running "flutter pub get" in teste...                                   
pub get failed (1; So, because teste depends on flutter_modular_test ^1.0.4, version solving failed.)`

**Comment by railsonsm** [comment]
I came here with the goal of opening this. Thank you.

**Comment by jacobaraujo7** [comment]
updated
