### ISSUE TITLE
I get this errors when running slidy start and flutter pub get, there's an incompatibility with flutter_modular_test and mobx_codegen, i had to remove them to flutter pub get run the dependencies //  Eu tive esses erros ao rodar o slidy start e depois o flutter pub get, parece haver uma incompatibilidade com as  versões do flutter_modular_test e mobx_codegen, precisei remover elas parece instalar as outras dependencias

### ISSUE THREAD

**Issue by gsllucas** [Flutterando/slidy#266]
$ flutter pub get
Because flutter_modular_test >=1.0.2 depends on flutter_modular ^3.4.1+1 and lol depends on flutter_modular ^4.0.1+2, flutter_modular_test >=1.0.2 is 
forbidden.
So, because lol depends on flutter_modular_test ^1.0.4, version solving failed.
Running "flutter pub get" in lol...
pub get failed (1; So, because lol depends on flutter_modular_test ^1.0.4, version solving failed.)

$ flutter pub get
Because mobx_codegen >=2.0.3 depends on analyzer ^2.0.0 which depends on meta ^1.7.0, mobx_codegen >=2.0.3 requires meta ^1.7.0.
And because every version of flutter_test from sdk depends on meta 1.3.0, mobx_codegen >=2.0.3 is incompatible with flutter_test from sdk.
So, because lol depends on both flutter_test any from sdk and mobx_codegen ^2.0.3, version solving failed.
Running "flutter pub get" in lol...
pub get failed (1; So, because lol depends on both flutter_test any from sdk and mobx_codegen ^2.0.3, version solving failed.)

**Comment by jamesldr** [comment]
Acredito que não dá problema se você remover as versões das libs no pubspec também, parece ser só incompatibilidade das versões especificadas lá.
