### ISSUE TITLE
slidy generate module modules/name -c

### ISSUE THREAD

**Issue by lucascorrea30** [Flutterando/slidy#269]
Slidy não está gerando o modulo completo, apenas o "name_module.dart".

PS C:\[path]\[app_name]> slidy g module teste -c
SUCCESS: teste_module created
SUCCESS: teste_module_test created
Unhandled exception:
Bad state: No element
#0      Iterable.firstWhere (dart:core/iterable.dart:516)
#1      GenerateModuleSubCommand.run (file:///c:/programdata/chocolatey/lib/slidy/tools/source/bin/commands/sub_command/
generate_module_sub_command.dart)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:196)
<asynchronous suspension>
#3      main (file:///c:/programdata/chocolatey/lib/slidy/tools/source/bin/main.dart:22)
<asynchronous suspension>

**Comment by Jcarlos1982** [comment]
Mesmo problema aqui.

**Comment by jacobaraujo7** [comment]
fixed
