### ISSUE TITLE
Separador entre nome da classe e responsabilidade configurável

### ISSUE THREAD

**Issue by btd1337** [Flutterando/slidy#272]
Antes de qualquer coisa, gostaria parabenizar aos desenvolvedores por este ótimo trabalho feito entre o Modular e o Slidy.

Dito isso, gostaria apenas de tocar em um ponto de melhoria para o Slidy:

É padrão dos frameworks que utilizam a estrutura de escopo modular, definir nomes usando o ponto antes do sufixo de tipo da classe, exemplo:

[Angular](https://angular.io/guide/styleguide#file-structure-conventions) e [Nest.js](https://docs.nestjs.com/modules#feature-modules)

```
// nome-classe.tipo-classe

service-providers.module.ts
service-providers.controller.ts
service-providers.service.ts 
```

O [Modular](https://github.com/Flutterando/modular) traz este conceito de estrutura de escopo modular, e até mesmo faz uso dos sufixos de `tipo-clase`, porém o detalhe que se perdeu no caminho é que o ponto para separar as responsabilidades, não é seguido pelo `Slidy`, que mantém tudo separado pelo `_`, tanto os separadores do nome das classes, quanto o seu sufixo de responsabilidade.

O ponto que esta issue traz é:

É possível adicionar uma opção customizável ao `Slidy` que permita que o time de desenvolvimento possa optar entre usar o `_`, ou o `ponto`, que já é o padrão nos outros frameworks, para fazer essa separação entre responsabilidades dentro do nome do arquivo?

**Comment by jacobaraujo7** [comment]
Estamos trabalhando com o mason para o futuro de nossos geradores de código. Com isso teremos mais configurações. Acredito que no futuro teremos isso e mais um pouco.
