### ISSUE TITLE
Brew installation in docs but not on brew.sh 

### ISSUE THREAD

**Issue by benjaminschreck** [Flutterando/slidy#274]
The installation of slidy with brew doesn't work. 

Warning: No available formula with the name "slidy". Did you mean slides or solid?
==> Searching for similarly named formulae...
These similarly named formulae were found:
slides                                   solid
To install one of them, run (for example):
  brew install slides
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by jacobaraujo7** [comment]
fixed in doc
