### ISSUE TITLE
Uso de metodos depreciados ao usar o slidy start

### ISSUE THREAD

**Issue by beto-ouverney** [Flutterando/slidy#275]
Ao usar o slidy start  e implementar o Modular, o slidy usa Modular.State que esta depreciado. e nao Modular.get()

**Comment by beto-ouverney** [comment]
tem este problema tb, Because mobx_codegen >=2.0.5 depends on build ^2.2.1 and modular_codegen 3.0.4 depends on build >=2.1.0 <2.2.0, mobx_codegen >=2.0.5 is incompatible with modular_codegen 3.0.4.

**Comment by jacobaraujo7** [comment]
fixed
