### ISSUE TITLE
Não consigo instalar o slidy no linux ubuntu 22.04.01 LTS

### ISSUE THREAD

**Issue by kauantorrisi** [Flutterando/slidy#278]
recentemente mudei meu sistema operacional para o Linux e eu só usava windows antes disso.
no windows consegui baixar o slidy através do chocolatey. aqui no linux vi que tinha que utilizar o homebrew, não consegui através do homebrew pois ele fica travado em uma etapa do processo. 
então decidi baixar atráves do comando "flutter pub global activate slidy", e aparentemente tinha dado certo.
só que quando vou executar algum comando do slidy me retorna o seguinte erro: 
"/usr/bin/slidy: 17: exec: /usr/bin/src/dart: not found"
alguém pode me ajudar? é algo que eu fiz errado?
desde já, obrigado pela atenção!

**Comment by kauantorrisi** [comment]
Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 5.15.0-56-generic,
    locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by enzodanjour** [comment]
@kauantorrisi faz assim:

1. no terminal digite `cd ~`
2. em seguida `nano .bashrc` se quiser outro editor só trocar o nano com seu editor de preferência (code, vim,vi)
3. adicione a seguinte linha no final do seu arquivo `export PATH=$PATH:/home/enzo/.pub-cache/bin`
4. salve as alterações(no caso do nano é ctrl+o em seguida enter e depois ctrl+x)

rode depois o comando para instalar o slidy com o dart

**Comment by kauantorrisi** [comment]
muito obrigado, consegui!
