### ISSUE TITLE
Sugestão: Geração de objetos de serviços

### ISSUE THREAD

**Issue by AndreNeves97** [Flutterando/slidy#28]
Boa noite.

Gostaria de sugerir um comando para a geração de `services: `slidy generate service [nome]`. Senti falta dessa nomenclatura quando fui organizar meu projeto. Ao meu ver, seria algo semelhante ao repositório, com o diferencial de que o repositório seria usado como "fonte" de dados de entidades, e serviços seriam algo como serviços de autenticação e acesso à api, algo semelhante ao que existe no Angular.

Me corrijam se eu estiver equivocado. 
Obrigado.

**Comment by jacobaraujo7** [comment]
Está absolutamente certo.
Vanos pensar em uma forma de adicionar essa nomeclatura como aliase do repository
