### ISSUE TITLE
Sugestão: Comandos de geração automática de código

### ISSUE THREAD

**Issue by AndreNeves97** [Flutterando/slidy#29]
Boa noite.

Gostaria de sugerir a implementação de uma classe de comandos para geração automática de código. A primeira delas seria o acionamento do módulo do package json_serializable (https://flutter.dev/docs/development/data-and-backend/json)

Obrigado

**Comment by jacobaraujo7** [comment]
Adicionamos o comando Script no pubspec.
Vc pode adicionar no pubspec.yaml um parametro chamado scripts.
Então vc consegue automatizar alguns códigos comuns como por exemplo o do json serializable
ex:
```
scripts:
   jsonb: flutter pub run build_runner build
```

Então basta chamar:
`slidy run jsonb`

**Comment by AndreNeves97** [comment]
Ok, obrigado!
