### ISSUE TITLE
Sugestão: Geração de estrutura de pastas vazias no slidy start

### ISSUE THREAD

**Issue by yuridiniz** [Flutterando/slidy#31]
Com a proposta do projeto de definir uma estrutura básica para a aplicação, acredito que deveria criar as pastas de repository, shared, blocs para que desenvolvedor não perca tempo pensando onde vai colocar cada coisa, como sugestão, acredito ser uma boa estrutura:

```
/app
|_ /pages
|_ /shared
    |_ /blocs
    |_ /model
    |_ /repository
```

Ou pode desconsiderar a pasta shared e colocar todas as pastinhas em app, mas a sugestão está aberta para discussão, caso julguem relevante

**Comment by jacobaraujo7** [comment]
Estamos testando uma nova estrutura.
Use o comando slidy start -c para gerar um projeto mais completo
