### ISSUE TITLE
Sugestão: comando para adicionar assets e fontes

### ISSUE THREAD

**Issue by henriquearthur** [Flutterando/slidy#40]
Seria interessante um comando para adicionar arquivos e pastas como `assets` e como fontes no pubspec.yaml.

Algo como ler o conteúdo de uma pasta e adicionar os arquivos dela como assets/fontes no pubspec. Porém as fontes tem seus `weight`, não sei se é possível automatizar eles.

**Comment by jacobaraujo7** [comment]
hoje vc pode definir uma pastar inteira no pubspec, tudo que estará lá vai funcionar.

assets:
   - assets/

**Comment by henriquearthur** [comment]
> hoje vc pode definir uma pastar inteira no pubspec, tudo que estará lá vai funcionar.
> 
> assets:
> 
> * assets/

Talvez de fato não haja necessidade de um comando pra adicionar assets.

Mas ainda acho interessante um comando para adicionar fontes.

Quando temos algo assim:

	flutter:
	  fonts:
	    - family: Raleway
	      fonts:
	        - asset: fonts/Raleway-Regular.ttf
	        - asset: fonts/Raleway-Italic.ttf
	          style: italic
	    - family: RobotoMono
	      fonts:
	        - asset: fonts/RobotoMono-Regular.ttf
	        - asset: fonts/RobotoMono-Bold.ttf
	          weight: 700

ou

	flutter:
	  fonts:
	    - family: Source Sans Pro
	      fonts:
	        - asset: assets/fonts/SourceSansPro-Light.ttf
	          weight: 300
	        - asset: assets/fonts/SourceSansPro-Regular.ttf
	        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
	          weight: 600
	        - asset: assets/fonts/SourceSansPro-Bold.ttf
	          weight: 700

Seria interessante executar um comando para adicionar as fontes como `slidy generate fonts assets/fonts` e o slidy inferir automaticamente os `weight` e `style: italic` e adicionar no pubspec.yaml dos arquivos de fonte em `assets/fonts`.

Mas isso seria algo pra pura **conveniência**, fazer isso manualmente não leva nem 1 minuto. Poderia até acostumar mal principalmente os iniciantes ao adicionar fontes com um único comando.

_~~eu só gosto de automatizar as coisas.~~_

Dependendo do escopo que o slidy quer atingir, talvez isso nem seja de fato uma boa ideia.

**Comment by rodrigolmacedo** [comment]
Existe a possibilidade de gerar o template do keystore também? ou é algo mais específico?
Entre outros ex:
> signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
   }

**Comment by jacobaraujo7** [comment]
@rodrigolmacedo existe sim, mas o gradle atualiza demais, e pode causar algum problema na configuração dependendo do processo.
Mas estou marcando sua issue no todo do project, se alguem se interessar em fazer e passar nos testes estará como nova feature

**Comment by jacobaraujo7** [comment]
@henriquearthur Já esta em produção essa issue

**Comment by Bwolfs2** [comment]
Um dos problemas foi resolvido com a https://pub.dev/packages/google_fonts
=D

E como a solucao dos assets com "assets/" foi resolvida e tida como desnecessaria, estou fechando a issue
