### ISSUE TITLE
Pequena atualização no comando pub para instalar o Slidy

### ISSUE THREAD

**Issue by jpvibes** [Flutterando/slidy#44]
Olá pessoal do Flutterando!
Gostaria de agradecer por essa incrível CLI!

Bom, eu tive um pequeno problema na hora da instalação. Ao utilizar o comando:
`flutter pub global activate slidy` 
eu obtive o erro `Can't load Kernel binary: Invalid kernel binary format version. No active package slidy.`

A solução foi tirar o flutter ficando somente  `pub global activate slidy`

**Comment by jacobaraujo7** [comment]
Obrigadão brother!
Tenta atualizar o seu Flutter, talvez o seu dart n esteja na última versao.

**Comment by jpvibes** [comment]
Nada Brother!
Está sim Jacob
Testei tanto na versão dev quanto na versão stable

Ambos só funcionaram usando o comando `pub global activate `
Isso foi no Win 10 pelo CMD/PowerShell

**Comment by jacobaraujo7** [comment]
Puxa, cê tiver lá pelo flutterando, vamos fazer uma call pra ver oq ocorre na sua maquina, ai a gente já corrige e atualiza aqui. Eu to querendo que o slidy rode direto no dart do flutter, para que as pessoas não precisem baixar a VM

**Comment by jpvibes** [comment]
Muito obrigado pela disposição!
O meu está rodando tranquilo mas só foi pela VM :(
Não sei se foi um problema do ruindows ou se foi porque eu estava com a VM do Dart + Flutter no meu path

Hoje eu irei instalar no meu Linux aí aproveito e faço esse teste e retorno por aqui :D

**Comment by wmattei** [comment]
Adicione `export PATH="$PATH":"/usr/lib/dart/bin"` ao seu .bashrc, .bash_profile, .zshrc, etc...

**Comment by Bwolfs2** [comment]
Resolvido? Podemos Fechar a Issue?

**Comment by jacobaraujo7** [comment]
Vou fechar a issue por agora, mas qualquer coisa só reabri-la! Obrigado

**Comment by jpvibes** [comment]
Oi gente :D
Mil desculpas. Acabei esquecendo de comentar. 
Gostaria de dizer que realmente só obtive esse problema no win 10
Instalando no Fedora / Ubuntu ocorreu tudo bem

Eu realmente não sei o que aconteceu no windows mas, está tudo tranquilo hahaha
Muito obrigado pela atencao :D

**Comment by distu** [comment]
export PATH="$PATH":"$HOME/.pub-cache/bin"

**Comment by marcelopinheiromocellin** [comment]
No meu nao funciona
me mostra assim no cmd
C:\>pub global activate slidy
"pub" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by diegosayron** [comment]
> No meu nao funciona
> me mostra assim no cmd
> C:>pub global activate slidy
> "pub" no se reconoce como un comando interno o externo,
> programa o archivo por lotes ejecutable.

O meu também informa a mesma coisa.
(Windows)

**Comment by MatheusNCarvalho** [comment]
@diegosayron 
eu conseguir resolver seguindo o tutorial abaixo:
[https://medium.com/flutter-comunidade-br/iniciando-no-flutter-parte-2-evoluindo-o-ambiente-de-desenvolvimento-com-o-slidy-88e633e159c6](url)

Obs.: Foi preciso reiniciar o Windows após adicionar as variáveis de ambiente

**Comment by dkawasaka** [comment]
Usei esse comando e deu certo
dart pub global activate slidy

**Comment by edsongaldino** [comment]
> dart pub global activate slidy

Funcionou pra mim tbm
