### ISSUE TITLE
Sugestão: Criação de pacote para Custom Schematics

### ISSUE THREAD

**Issue by wmattei** [Flutterando/slidy#50]
Uma vez que o Slidy é baseado no @angular/schematics creio que seria interessante ter uma forma de permitir com que o usuário crie seus próprios Scaffold's, seguindo o conceito do `@angular-devkit/schematics` que entre outras features permite a criação de uma árvore virtual de arquivos base, que serão gerados na pasta do projeto, dentro desses arquivos base é possível usar um parse de strings para printar variáveis no arquivo:

Ex: 
```typescript
getBaseUrl(): string {
       // dasherize é uma função helper do angular schematics que transforma a string em kebab-case
       return `${environment.URL_API}/<%= dasherize(name) %>`;
}
```
Exemplo de aplicações:
 
Usuários que queiram criar boilerplates para diversos projetos poderiam com apenas um comando gerar os temas que queiram, fazer toda a autenticação, montar uma estrutura de testes, entre outros...

Exemplo de Angular schemtaics `https://github.com/dploy-team/rapi-schematics`

Caso a equipe tenha interesse posso trabalhar em um PR de um MVP disso.

**Comment by kellvembarbosa** [comment]
Up

**Comment by jacobaraujo7** [comment]
Já estamos com testes internos com a função TEMPLATES. Estamos criando baseado em Pipeline

**Comment by jacobaraujo7** [comment]
Estamos direcionando os esforços do Generator para o Mason.
