### ISSUE TITLE
Flutter falha em pegar o pacote

### ISSUE THREAD

**Issue by pauloantonelli** [Flutterando/slidy#51]
Quando insiro o pacote em dependecies, tanto bloc_pattern: ^2.3.2, quando bloc_pattern: ^2.4.4 da o erro: A package may not list itself as a dependency.

A saida do console:
[bloc_pattern] flutter packages get
Running "flutter pub get" in bloc_pattern...                    
Error on line 27, column 3 of pubspec.yaml: A package may not list itself as a dependency.

   ╷

27 │   bloc_pattern: ^2.3.2

   │   ^^^^^^^^^^^^
   ╵
pub get failed (65)
exit code 65

Algum jeito de resolver esse problema?

**Comment by emendes28** [comment]
Cara tenta remover e dar apagar seu pubspec.lock e tenta instalar com o slidy install bloc_pattern eu tentei em 2 projetos aqui e não apareceu esse problema se o problema persistir tenta dar mais detalhes (y)

**Comment by Bwolfs2** [comment]
Conseguiu resolver? Senao tem como mostrar o seu pubspec.yaml?

**Comment by pauloantonelli** [comment]
> Cara tenta remover e dar apagar seu pubspec.lock e tenta instalar com o slidy install bloc_pattern eu tentei em 2 projetos aqui e não apareceu esse problema se o problema persistir tenta dar mais detalhes (y)

VAlew, quando chegar em casa vou tentar essa solução @emendes28 e volto aqui

**Comment by pauloantonelli** [comment]
> Conseguiu resolver? Senao tem como mostrar o seu pubspec.yaml?

Ainda nao! Tentei varias vezes instalar o pacote ontem mas nao consegui. 
Mais tarde vou tentar a solucao do @emendes28 e volto aqui pra deixar o resultado @Bwolfs2

**Comment by jacobaraujo7** [comment]
Remove o pacote e tenta instalar diretamente pelo
slidy i bloc_pattern

**Comment by pauloantonelli** [comment]
> slidy i bloc_pattern

Jacob tentei isntalar pelo slidy e da o mesmo erro: 

[bloc_pattern] flutter packages get
Running "flutter pub get" in bloc_pattern...                    
Error on line 20, column 3 of pubspec.yaml: A package may not list itself as a dependency.

   ╷
20 │   bloc_pattern: ^2.4.4


   │   ^^^^^^^^^^^^

   ╵
pub get failed (65)
exit code 65
[bloc_pattern] flutter packages get
Running "flutter pub get" in bloc_pattern...                        0.5s
exit code 0
[bloc_pattern] flutter packages get
Running "flutter pub get" in bloc_pattern...                    
Error on line 20, column 3 of pubspec.yaml: A package may not list itself as a dependency.

   ╷


20 │   bloc_pattern: ^2.4.4
   │   ^^^^^^^^^^^^

   ╵
pub get failed (65)
exit code 65

**Comment by pauloantonelli** [comment]
> Conseguiu resolver? Senao tem como mostrar o seu pubspec.yaml?

meu pubspec.yaml esta assim no momento(com a tentativa do slidy de adicional o bloc_pattern:

name: bloc_pattern
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc_pattern: ^2.4.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  slidy: ^1.1.4
  rxdart: ^0.22.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by pauloantonelli** [comment]
> Cara tenta remover e dar apagar seu pubspec.lock e tenta instalar com o slidy install bloc_pattern eu tentei em 2 projetos aqui e não apareceu esse problema se o problema persistir tenta dar mais detalhes (y)

tentei tambem deletar o .lock e dar um get em tudo de novo mas o resultado é o mesmo.

Estou com a ultima versao stable do dart sdk instalado

**Comment by pauloantonelli** [comment]
Subi aqui pro git para caso alguem puder dar uma olhadinha e me ajudar a continuar a estudar o bloc: https://github.com/pauloantonelli/curso_flutter_flutterando
Agradeço de antemão rss

**Comment by eRoberio** [comment]
Estou com o mesmo problema !

**Comment by pauloantonelli** [comment]
> Estou com o mesmo problema !

@eRoberio eu resolvi esse problema trocando o nome do projeto no pubspec.yaml
la eu tinha usado o nome slidy no nome do projeto e dava problemas.
Tenta e qualquer coisa avisa por favor

**Comment by adrianohleroy** [comment]
O seu projeto tem o mesmo nome do pacote, "bloc_pattern", mude o nome do seu projeto.
