### ISSUE TITLE
Como dar o slidy start[force] nessa nova versão?

### ISSUE THREAD

**Issue by toshiossada** [Flutterando/slidy#61]
Antes eu dava o slidy start -f para forçar e deletar os arquivos da pasta lib do projeto, mas agora nesta versão do slidy o -f é para criar utilizando o flutter_bloc, qual é o substituto para o force agora?

**Comment by jacobaraujo7** [comment]
A gente viu que ter uma possibilidade de "forçar" apagar os arquivos da lib era muito perigoso e poderia ser aproveitada por algum maware ou desentendimento do usuário.
Então tornamos o slidy start não imperativo, e assim, será necessário sempre uma confirmação do usuário para executar o comando.

Também atribuimos o -f ao --flutter_bloc

**Comment by Bwolfs2** [comment]
Tem que colocar para aceitar tanto Y quando y pq minusculo nao ta rolando

**Comment by jacobaraujo7** [comment]
A ideia é que não aceite o y lowercase, justamente para previnir algum estrago não premeditado
