### ISSUE TITLE
Sugestão: Gerar assinatura de apps Android (keystore)

### ISSUE THREAD

**Issue by rodrigolmacedo** [Flutterando/slidy#62]
Gerar keystore e configuração de assinatura do Android em projetos flutter.

**Comment by jacobaraujo7** [comment]
Você pode usar o comando "slidy run" para executar algumas rotinas que podem ser programadas no próprio pubspec.yaml
Por exemplo

```
scripts:
    genkey: keytool -genkey -v -keystore ~/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key
```

Ai só executar com o commando 
"slidy run genkey"

**Comment by rodrigolmacedo** [comment]
> 
> 
> Você pode usar o comando "slidy run" para executar algumas rotinas que podem ser programadas no próprio pubspec.yaml
> Por exemplo
> 
> ```
> scripts:
>     genkey: keytool -genkey -v -keystore ~/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key
> ```
> 
> Ai só executar com o commando
> "slidy run genkey"

Obrigado, nem tinha lembrado disso! XD
