### ISSUE TITLE
depends on build_runner >=1.7.2 

### ISSUE THREAD

**Issue by iberno** [Flutterando/slidy#68]
Bom Dia Pessoal, 

Está apresentando esse probleminha na criação do projeto MOBX com Slidy.
Realizei varias pesquisas mas não consegui resolver.
Minha versão do DART é 2.6.1.

Because #APP_NAME depends on build_runner >=1.7.2 which requires SDK version >=2.6.0-dev.8.0 <3.0.0, version solving failed.
pub get failed (1)

**Comment by kellvembarbosa** [comment]
Também tive o mesmo problema hoje... Mesmo fazendo o Upgrade para o dart sdk 2.6.1 o erro continuou... 

`dev_dependencies:
  mobx_codegen: ^0.3.10+1
  build_runner:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
`

Resolveu para mim remover a versão do **build_runner:**

**Comment by iberno** [comment]
Boa Tarde!!!
 depois de bater bastante a cabeça... realizei a instalação do Flutter na versão DEV 1.12.3-pre.43 e Dart na versão 2.7, sim... agora sim funcionou..

1 - remova as variáveis de ambiente (PATH)
2 - Exclua os arquivos do Flutter e Tools 
3 - Baixe a versão DEV, reconfigure as variáveis e em seguida abra um terminal e execute Flutter --version... ele se encarregará de baixar o DART da versão e fará a configuração das dependencias
4 -  Re-instale  Slidy... "flutter pub global activate slidy"

Magica.... Funcionou comigo no Windows... vou testar no Ubuntu.

**Comment by iberno** [comment]
> Boa Tarde!!!
> depois de bater bastante a cabeça... realizei a instalação do Flutter na versão DEV 1.12.3-pre.43 e Dart na versão 2.7, sim... agora sim funcionou..
> 
> 1 - remova as variáveis de ambiente (PATH)
> 2 - Exclua os arquivos do Flutter e Tools
> 3 - Baixe a versão DEV, reconfigure as variáveis e em seguida abra um terminal e execute Flutter --version... ele se encarregará de baixar o DART da versão e fará a configuração das dependencias
> 4 - Re-instale Slidy... "flutter pub global activate slidy"
> 
> Magica.... Funcionou comigo no Windows... vou testar no Ubuntu.

Agora vou pro tutorial do Jacob....
