### ISSUE TITLE
Adicionar hive no start do projeto como um opcional

### ISSUE THREAD

**Issue by kellvembarbosa** [Flutterando/slidy#69]
Gostei de trabalhar com o HIVE talvez seria interessante um comando para já iniciar o projeto com o hive 
comando --hive 

e já iniciar com o arquivo shared/service/local_storage.dart 

```
import 'dart:async';

import 'package:bloc_pattern/bloc_pattern.dart';
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart' as path_provider;

class LocalStorageService extends Disposable {
  Completer<Box> completer = Completer<Box>();
  
  LocalStorageService(){
    _initDB();
  }

  _initDB() async {
    final directory = await path_provider.getApplicationDocumentsDirectory();
    Hive.init(directory.path);
    //final box = await Hive.openBox("favoritos"); // Nome da caixa
    //if(!completer.isCompleted) completer.complete(box);
  }

  @override
  void dispose() {
    final box = await completer.future;
    box.close();
  }
}
```

**Comment by jacobaraujo7** [comment]
Obrigado pelo feedback!
O Hive é muito bom, estou aguardando eles concertarem um problema que acontecem nós testes unitários quando abrimos o banco na memória. 

Estamos terminando a base do slidy para poder aceitar templates customizados, aí chegaremos nesses templates e módulos inteiros com códigos criados pela comunidade.

**Comment by kellvembarbosa** [comment]
Boa, isso vai ser perfeito! 

Estou desenvolvendo muito bem com o auxilo do slidy! 
Estou ai torcedo para cada vez mais melhorar abraços...

**Comment by kellvembarbosa** [comment]
Ainda existe possibilidade de poder adicionar arquivos customizados ao comando start? 
Por ex eu criei alguns arquivos que seria essencial para startar em todos os meus projetos, isso faz com que eu diminua o uso do slidy no momento do start... 

Já é perfeito o slidy, mas seria ainda melhor se existir essa opção...
