### ISSUE TITLE
Ao gerar teste não é criado o teste de Page

### ISSUE THREAD

**Issue by henriquearthur** [Flutterando/slidy#77]
Quando criamos um módulo completo com `slidy g m -c modules/exemplo` são criados dois arquivos de teste:
- exemplo_bloc_test.dart
- exemplo_page_test.dart

Porém, se tivermos um módulo já existente mas que não possui testes e utilizarmos `slidy g t modules/exemplo`, o teste `exemplo_page_test.dart` não será criado, apenas será criado o `exemplo_bloc_test.dart`.

Eu já usava o slidy antes dos recursos pra gerar teste, por isso tenho vários módulos que não foram criados com testes e me deparei com esse bug.

**Comment by Bwolfs2** [comment]
Fixed
