### ISSUE TITLE
Adicionar warning para comando fora do diretório do projeto 

### ISSUE THREAD

**Issue by danilomedeiros** [Flutterando/slidy#78]
~$ slidy start --flutter_bloc
Starting a new project with flutter_bloc

Unhandled exception:
Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:144:5)
#1      PubSpec.load (package:slidy/src/utils/pubspec.dart:15:10)
<asynchronous suspension>
#2      getPubSpec (package:slidy/src/utils/utils.dart:45:18)
<asynchronous suspension>
#3      getNamePackage (package:slidy/src/utils/utils.dart:22:24)
<asynchronous suspension>
#4      start (package:slidy/src/modules/start.dart:62:26)
<asynchronous suspension>
#5      StartCommand.run (package:slidy/src/command/start_command.dart:32:5)
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#8      new Future.sync (dart:async/future.dart:224:31)
#9      CommandRunner.run (package:args/command_runner.dart:112:14)
#10     executeCommand (file:///home/danilo/dev/flutter_linux_v1.9.1%20hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/slidy-1.2.2/bin/main.dart:33:10)
#11     main (file:///home/danilo/dev/flutter_linux_v1.9.1%20hotfix.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/slidy-1.2.2/bin/main.dart:12:5)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by Bwolfs2** [comment]
essa issue esta causando SideEffect quando usamos o comando Slidy Create pois ele esta entendendo que o comando "slidy start" esta sendo executado fora da pasta.
Tem como corrigir isso @antonielliimma ?

**Comment by antonielliimma** [comment]
@Bwolfs2 bwol Tem sim!!!

Mando a PR hoje ainda!
