### ISSUE TITLE
Problema com underline no slidy generate

### ISSUE THREAD

**Issue by henriqueuller** [Flutterando/slidy#79]
Se executamos o seguinte comando `slidy g m modules/teste_up -c` em um projeto que utiliza MobX, ele remove o underline do do part no controller, fazendo com que o build_runner não consiga gerar o arquivo `teste_up_controller.g.dart`.

Exemplo do arquivo gerado:
```
import 'package:mobx/mobx.dart';

part 'testeup_controller.g.dart';

class TesteUpController = _TesteUpBase with _$TesteUpController;

abstract class _TesteUpBase with Store {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```

Fiz o teste colocando o underline manualmente e funcionou.
```
import 'package:mobx/mobx.dart';

part 'teste_up_controller.g.dart';

class TesteUpController = _TesteUpBase with _$TesteUpController;

abstract class _TesteUpBase with Store {
  @observable
  int value = 0;

  @action
  void increment() {
    value++;
  }
}
```

**Comment by jacobaraujo7** [comment]
Olá, obrigado por informar o bug.
Isso acontece quando removo os underlines para criar o cameCase do nome da classe. Precisarei ver como passarei o nome digitado para o template antes que formate o underline.

**Comment by Bwolfs2** [comment]
Fixed

**Comment by henriqueuller** [comment]
Valeu, obrigado pessoal!
