### ISSUE TITLE
Comando create para em "Starting a new project with flutter_bloc"

### ISSUE THREAD

**Issue by lukasgarcya** [Flutterando/slidy#81]
Quando crio um projeto através do comando: slidy create nomeprojeto para a execução em:

Starting a new project with flutter_bloc

WARN: WARNING! This command will delete everything inside the "lib /" and "test" folders.
Do you wish to continue? [Y]es or [n]o

Mesmo que digite Y não continua

**Comment by jacobaraujo7** [comment]
corrigido na versão 1.3.0
Obrigado por reportar o bug
