### ISSUE TITLE
O comando slidy create para em "WARN: What Provider System do you want to use?"

### ISSUE THREAD

**Issue by lukasgarcya** [Flutterando/slidy#82]
Mesmo digitando uma das opções, 1 ou 2, não continua a execução.

**Comment by jacobaraujo7** [comment]
estamos trabalhando nisso

**Comment by antonielliimma** [comment]
Boa noite @jacobaraujo7  Boa noite @Bwolfs2 

Rapaz tive o mesmo problema com slidy, esta sendo o meu primeiro contado com a ferramenta instalei ele agorinha depois de assistir ao vídeo de flutter modular no canal flutterando sensacional o conteúdo!

Mais vamos lar esse problema acontece quando se usar o comando `slidy start` fora da pasta de um projeto flutter!

@lukasgarcya então resolvi o meu problema criando o projeto com o comando `flutter create myapp
 && cd myapp`

Ai rodei o slidy e foi de boa!

@jacobaraujo7 @Bwolfs2 descobri isso após fazer um clone do repositório do slidy e começar a estudar os fontes, estou super disposto a criar a correção vou chamar vocês amanhã no telegram.

vlw Flutterandos!

**Comment by Bwolfs2** [comment]
Fixed, u need to change using arrows
