### ISSUE TITLE
Problema nas classes de testes gerando o modular

### ISSUE THREAD

**Issue by toshiossada** [Flutterando/slidy#83]
![image](https://user-images.githubusercontent.com/2637049/70996962-af90ee80-20b2-11ea-87eb-c3b098982e85.png)

Ao criar um projeto do 0 usando o modular (slidy start) as classes de testes são geradas com este erro do print (quando gero pages e widgets também ocorre a mesma coisa) a versão do slidy que estou utilizando é a  1.3.4

**Comment by Bwolfs2** [comment]
Fixed
