### ISSUE TITLE
Problema para instalar Slidy no macOs

### ISSUE THREAD

**Issue by develogo** [Flutterando/slidy#85]
Primeiramente, parabéns pelo Slidy, é incrivel.

Estou tendo problema para instalar o Slidy no macOs usando o seguinte comando(Meu shell é oh my zsh):
`flutter pub global activate slidy`

Adicionei o seguinte caminho ao meu shell conforme informado quando instalei:
`export PATH="$PATH":"$HOME/flutter/.pub-cache/bin"`

Quando tento rodar `slidy --version` recebo o seguinte erro:

> Can't load Kernel binary: Invalid kernel binary format version.
> No active package slidy.

`Flutter Doctor
`
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88,
>     locale pt-BR)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version
>     29.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3)
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.40.2)
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 1 category.

**Comment by jacobaraujo7** [comment]
muito obrigado,
Você poderia instalar diretamente na dart vm?
ai só usar
pub global activate slidy, acredito que rode melhor.

**Comment by develogo** [comment]
Consegui resolver da seguinte forma:

1- `brew upgrade dart`
2- `flutter pub global activate slidy`
 
Apenas isso funcionou, meu dart estava na versão 2.4.1 - 2019-08-07
