### ISSUE TITLE
add in documentation feature "scripts" in pubscpec

### ISSUE THREAD

**Issue by jacobaraujo7** [Flutterando/slidy#88]
Add feature "script" in documentation.
in pubspec.yaml
```
scripts:
  your-script: run script
```
exec
slidy run your-script

**Comment by lukelima** [comment]
Creio que isso já esteja na sessão "run":

### run:

Executa os scripts em pubspec.yaml:

```
slidy run open_folder
```

**Comment by Bwolfs2** [comment]
Boa @lukelima
