### ISSUE TITLE
Mobx não funciona Command start --mobx

### ISSUE THREAD

**Issue by moreirawebmaster** [Flutterando/slidy#89]
Olá galera.

Ao executar slidy start-mobx ou -m retorna a imformação:

Usage: slidy start [arguments]
-h, --help        Print this usage information.
-c, --complete    Create a complete flutter project with Themes separated of main.dart, named Routes and locales Strings configured

Versão utilizada 1.4.1

**Comment by conflited** [comment]
mesmo problema aqui

**Comment by knoonrx** [comment]
Aqui também mesmo problema

**Comment by Bwolfs2** [comment]
Pow esse comando mudou e eu esqueci de atualizar o Read-me, para vc rodar o comando vc precisa dar um Slidy Start e ele vai solicitar as opções bloc_pattern ou modular e depois disso vc seleciona mobx, flutter_bloc ou rxdart
