### ISSUE TITLE
slidy start --complete faz setup de localization, mas não adiciona no pubspec

### ISSUE THREAD

**Issue by alexwbuschle** [Flutterando/slidy#92]
Ao rodar o comando `slidy start --complete`, está adicionando a parte de localization no AppWidget, porém não adiciona os packages no pubspec.yml

Versão do slidy: 1.4.1

**Comment by Bwolfs2** [comment]
A forma de fazer a localization vai ser modificada e o --complete vai ser removido.
Estamos definindo qual package e como vai ser utilizada da melhor forma

**Comment by alexwbuschle** [comment]
ok, vou fechar a issue ;)
