### ISSUE TITLE
slidy start

### ISSUE THREAD

**Issue by tuskinhu** [Flutterando/slidy#94]
Boa Noite,

Após alguns testes com o slidy, não sei porquê o powershell do windows parou de funcionar e todos os comandos do start não eram mais possíveis de serem dados devido a confusão na tela.

![806624657_350596](https://user-images.githubusercontent.com/606731/71773207-f8acc380-2f37-11ea-8ab5-a769f2034a80.jpg)

Minha sugestão seria no comando start ser possível passar todas as respostas solicitadas, não necessitando mais nenhuma iteração do usuário.

**Comment by lukelima** [comment]
Acho bacana. Seria semelhante ao comando "install", onde as opções podem ser passadas por argumento na linha de comando. 

Posso criar um PR se ninguém for contra

**Comment by jacobaraujo7** [comment]
Acredito que seria uma boa feature. Aguardando seu PR @lukelima

**Comment by lukelima** [comment]
Beleza! Subirei hoje (13/01/2020) até as 19h

**Comment by lukelima** [comment]
https://github.com/Flutterando/slidy/pull/102
